### ISSUE TITLE
Cannot Install on Ubuntu 20.x "permission denied"

### ISSUE THREAD

**Issue by danfsd** [warrensbox/terraform-switcher#102]
I can't install TFSwitch on my Ubuntu Budgie 20.x system because of a permission error

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"
```

This is the error:

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9159  100  9159    0     0   111k      0 --:--:-- --:--:-- --:--:--  110k
warrensbox/terraform-switcher info checking GitHub for latest tag
warrensbox/terraform-switcher info found version: 0.8.832 for 0.8.832/linux/amd64
install: cannot create regular file '/usr/local/bin/tfswitch': Permission denied
```

Tried installing using sudo but nothing changes.

**Comment by warrensbox** [comment]
I am assuming you do not have permission to install `tfswitch` at this location `/usr/local/bin/`.
I would suggest that you create a path that you have access to. For example, your home path:

Can you try these steps:
1. Get the installer on to your machine:
`wget https://raw.githubusercontent.com/warrensbox/terraform-switcher/release/install.sh`
2. Make installer executable:
`chmod 755 install.sh`
3. Install `tfswitch` in a location you have permission:
`./install.sh -b $HOME/.bin`
4. Export your `.bin` into your path:
`export PATH=$PATH:$HOME/.bin`

You should probably add step 4 in your bash_profile or rc file.

**Comment by danfsd** [comment]
Hey @warrensbox, I've followed your steps and it's working now! Thanks :tada:
