### ISSUE TITLE
tfswitch list is very intrusive... Shouldn't trigger download of latest

### ISSUE THREAD

**Issue by marcellodesales** [warrensbox/terraform-switcher#111]
# tfswitch triggers download

* I just wanted to list all the versions currently installed without any downloads
* The switch verified that there's a new version and automatically downloaded without me asking

```console
$ tfswitch -l
Reading required version from terraform file, constraint: >= 0.12
Matched version: 0.13.5
Downloading https://releases.hashicorp.com/terraform/0.13.5/terraform_0.13.5_darwin_amd64.zip to terraform_0.13.5_darwin_amd64.zip
Downloading ...
^C
terraform_ps1:4: command not found: terraform
```

# Feature Request

* WIthout knowing the versions can break, I think this could avoid switching to new versions until asked

```
$ tfswitch -l 
```

* Maybe use a fetch 

```
$tfswitch --fetch
```

* I know I can change restrictions on my terraform file, but I think that's a bit intrusive to just switch automatically

**Comment by warrensbox** [comment]
This is a bug. I will look at this.
