### ISSUE TITLE
Brew Upgrade issue on MacOS 11

### ISSUE THREAD

**Issue by boonchu** [warrensbox/terraform-switcher#116]
Please help to investigate. I got this issue after OS upgrade to Big Sur.

```
==> Installing tfswitch from warrensbox/tap
==> Downloading https://github.com/warrensbox/terraform-switcher/releases/download/0.9.934/terraform-switcher_0.9.934_darwin_amd64
Already downloaded: /Users/bigchoo/Library/Caches/Homebrew/downloads/baa4aaef23f8e67006190b4c36a304c00cb079027c9f39e0ae83454a7f8c3154--terraform-switcher_0.9.934_darwin_amd64.tar.gz
Error: Your CLT does not support macOS 11.0.
It is either outdated or was modified.
Please update your CLT or delete it if no updates are available.
```

**Comment by boonchu** [comment]
tfswitch looks fine to me. Something might be wrong in brew package installer. I have the workaround for time being:

```
brew uninstall tfswitch
curl -L https://raw.githubusercontent.com/warrensbox/terraform-switcher/release/install.sh | bash
tfswitch -l
✔ 0.12.29 *recent
```

**Comment by warrensbox** [comment]
@boonchu yeah I guess the brew package installer has issues with the latest OS (Big Sur 11.0.1). I hope either the developers managing brew or the Mac OS team comes up with a remedy. I have not tested tfswtich on MacOS 11.X.X.

**Comment by versus** [comment]
Simplest solution that worked when upgrading to Big Sur. A clean install may not require the solution below. I believe there is some inconsistency with the way CLT is upgraded.

```
sudo rm -rf /Library/Developer/CommandLineTools
sudo xcode-select --install
```
