### ISSUE TITLE
snap package cannot use "~/.terraform.version" and "/usr/local/bin"

### ISSUE THREAD

**Issue by strowk** [warrensbox/terraform-switcher#117]
I've installed package from snap and running `tfswitch -b $HOME/bin` , it gives me 
```
Error while creating /home/user/.terraform.versions/terraform_0.13.5_linux_amd64.zip - open /home/user/.terraform.versions/terraform_0.13.5_linux_amd64.zip: permission denied
```
Running just `tfswitch --latest` complains about `/usr/local/bin` directory . Both places are not available from usual snap packages.

**Comment by warrensbox** [comment]
1. Are you running `tfswitch -b $HOME/bin/terraform` or `tfswitch -b $HOME/bin` ?
2. Do you have permission to write to the `$HOME/bin` directory (what do you see when you run `ls -l` on $HOME?

**Comment by strowk** [comment]
1. both give same result
1. I am owner  of $HOME/bin:
```
whoami
tim

ls -la $HOME | grep ' bin'
drwxrwxr-x  3 tim  tim   4096 Dez 14 16:50 bin

```

Note:

I've uninstalled tfswitch installed using Troubleshooting guilde and installed snap package again to reproduce it again

**Comment by strowk** [comment]
From what I see here 
https://forum.snapcraft.io/t/access-to-specific-hidden-file-path-in-users-home/6948
it looks like 
1. problem is in ~/.terraform.versions 
2. snap does not allow to use hidden dirs in home

So either tfswitch in snap package should automatically use different folder (maybe ~/snap/tfswitch ? I see this folder has been created by snap) or at least allow to customize it.

**Comment by warrensbox** [comment]
@strowk  perhaps I can allow users to customize it.
Thank you for bringing this up. I will find some time to do this before the end of the year. Hopefully, I can release this fix in January. 
In the source code: -
```
getInstallLocation() //only downloads the terraform bins into the home directory in .terraform.versions
.
.
.
installLocation = usr.HomeDir + installPath //where installPath = "/.terraform.versions/"
```
I can make this `getInstallLocation()` customizable where users can provide a location for all terraform binaries. Again, I can only get to this by the end of the year. If you know `go` and would like to contribute, I would be happy to review and merge your code as well.

I will let you know once I have implemented this. Thank you for bringing this up.

**Comment by strowk** [comment]
Just want to add one note here - I see it would go better if either there would be note in installation doc and in description here https://snapcraft.io/tfswitch , that snap package requires additional configuration, or binary should somehow understand that it's running as a snap package and change path automatically. Otherwise everyone who install snap package would found themselves in this issue :) 

I suspect that detection run from snap should not be very hard. Probably checking any of these env vars would do - https://snapcraft.io/docs/environment-variables

**Comment by applike-ss** [comment]
Is there any progress on this? I would actually like to use a snap version of tfswitch :+1:

**Comment by strowk** [comment]
Well, I managed to reproduce that issue on CI here - https://github.com/strowk/terraform-switcher/blob/5e93ed57d0dc94edc73d1b0078c36eb404774510/.circleci/config.yml . So that could be used in this project to check if the stuff actually works after releasing. 
This is how reproduced fail looks like: 
https://app.circleci.com/pipelines/github/strowk/terraform-switcher/8/workflows/02ecaec3-3a33-4e2e-9352-aaf323245d73/jobs/8

Additionally if CI configured a bit less complex (without -b flag) another bug is reproduced here:
https://app.circleci.com/pipelines/github/strowk/terraform-switcher/5/workflows/81784b1e-79d5-4298-9eb0-93f3e67ca405/jobs/5 
```
Error - Binary path does not exist: /usr/local/bin
Create binary path: /usr/local/bin for terraform installation
```

I guess that if you want to actually make snap package work, then this other thing should be addressed too, otherwise testing procedure would look weird. Though I suppose that could work too if needed

**Comment by warrensbox** [comment]
I am requesting snapcraft  for access to user home:
https://forum.snapcraft.io/t/request-interface-personal-files-read-write/25277/3

If you all can upvote the issue, it would be great!

**Comment by strowi** [comment]
Hi, just wanted to leave my 2ct here:
Using Gitlab for ci/cd. 
Gitlab allows specifying a cache from the build-dir (has to be withing the build-dir!). 
It would be very helpful if there was a cli-parameter to allow changing  `~/.terraform.versions/` to e.g. `$PWD/.terraform.versions`.
This way the executables could be cached via Gitlabs mechanism, and there is no/less need to download these from external ressources in every pipeline.

In gitlab-ci.yml this would look sth like this;
```yaml
.plan:
  stage: plan
  allow_failure: false
  cache:
    key: "${CI_COMMIT_REF_SLUG}"
    paths:
      - ${CI_PROJECT_PATH}/.terraform.versions
  script:
    - terraform switch -cache=$CI_PROJECT_PATH/.terraform.versions
    - terraform init
    - terraform validate
...
 ```

**Comment by toast-gear** [comment]
I also have a need to be able to set a custom the location for the `.terraform.versions` directory.

**Comment by strowi** [comment]
any progress on this one?
