### ISSUE TITLE
Supporting latest implicit version

### ISSUE THREAD

**Issue by skyzyx** [warrensbox/terraform-switcher#118]
**Context:**

My team develops Terraform modules, and we want to test against certain major versions of Terraform (e.g., 0.12, 0.13, 0.14).

We've been using `tfswitch` to help automatically install the right version of Terraform for deployments, etc., but it's been more challenging to use it for things like 0.12.latest, or 0.13.latest.

**Request:**

If would be handy to be able to support **implicit** versions, semantic versioning-like.

For example:

```bash
# latest supported (implicit)
tfswitch

# download 0.13.0 (explicit)
tfswitch 0.13.0

# download 0.13.5 (explicit)
tfswitch 0.13.5

# download 0.13.5 (implicit; latest)
tfswitch 0.13
```

Or maybe use a flag instead:

```bash
# download 0.13.5 (latest)
tfswitch --latest 0.13

# error! no such version!
tfswitch 0.13
```

One thing that would have been helpful during the 0.14 pre-releases would have been something to give me the latest pre-release for a version before the final release was out. I could hook this up to Travis-CI or Circle-CI or whatever, and ignore failures, but it would give me a sense about forward compatibility.

```bash
# download 0.14-rc1 before 0.14.0 was out
tfswitch --latest-pre 0.14
```

**Comment by warrensbox** [comment]
This is plausible. I can try to implement this by the end of this year.

**Comment by warrensbox** [comment]
### Install latest version only
1. Install the latest stable version only.
2. Run `tfswitch -u` or `tfswitch --latest`.
3. Hit **Enter** to install.
### Install latest implicit version for stable releases
1. Install the latest implicit stable version.
2. Ex: `tfswitch -s 0.13` or `tfswitch --latest-stable 0.13` downloads 0.13.6 (latest) version.
3. Hit **Enter** to install.
### Install latest implicit version for beta, alpha and release candidates(rc)
1. Install the latest implicit pre-release version.
2. Ex: `tfswitch -p 0.13` or `tfswitch --latest-pre 0.13` downloads 0.13.0-rc1 (latest) version.
3. Hit **Enter** to install.

Please upgrade to the latest version (Version: 0.10.958):
https://tfswitch.warrensbox.com/Upgrade-or-Uninstall/

Please help me test this version and let me know if you find any issues. Thank you.

**Comment by wderezin** [comment]
It's functioning per the documentation but the version is ignored with `--latest` instead of creating an error.

```
# tfswitch --latest 0.13
Switched terraform to version "0.14.4"
```

**Comment by warrensbox** [comment]
@wderezin 
`tfswitch --latest` will get the **latest of the latest stable** terraform version. At this moment, it is `0.14.4`.

`tfswitch --latest-stable 0.13` or `tfswitch -s 0.13` will get  `0.13.6` <- latest version of terraform 13.

`tfswitch --latest-pre 0.13` or `tfswitch -p 0.13`  will get `0.13.0-rc1` <- latest version of pre-release terraform 13.

In your case, please use `--latest-stable` or. `--latest-pre` (or the shorthands). 
When I was refactoring the code, the library I was using, allowed the `latest` parameter to be used either as a boolean parameter or string parameter, but not both.
