### ISSUE TITLE
Snap package has not been updated since September 2020

### ISSUE THREAD

**Issue by julian-alarcon** [warrensbox/terraform-switcher#126]
Checking the website of Snapcraft I see that the latest version available is 0.7.817 but current version is 0.10.958 from 8 days ago.

https://snapcraft.io/tfswitch

**Comment by warrensbox** [comment]
@julian-alarcon it should be available now. Looks like the automated process to release on snapcraft was not working earlier.
See updated version here: https://snapcraft.io/tfswitch
`snap refresh tfswitch --stable` to get the latest version
