### ISSUE TITLE
cannot install tfswitch as normal user, 

### ISSUE THREAD

**Issue by Balakrishna625** [warrensbox/terraform-switcher#127]

**Comment by beanaroo** [comment]
You can. Helpful instructions are provided on the [Troubleshooting](https://tfswitch.warrensbox.com/Troubleshoot/) page.

I'm a bit disappointed this is not the default behaviour. `pyenv`, `nvm` all operate within the user directory. They also allow you to work on different versions on multiple projects at the same time.

tfswitch appears to modify the global context.

**Comment by Xat59** [comment]
To install `tfswitch` as unprivileged user, use the `-b` option of the `install.sh` script. It defines the path directory of the `tfswitch` binary :

```
$ wget raw.githubusercontent.com/warrensbox/terraform-switcher/release/install.sh
$ bash install.sh -b ~/.local/bin
warrensbox/terraform-switcher info checking GitHub for latest tag
warrensbox/terraform-switcher info found version: 0.10.1010 for 0.10.1010/linux/amd64
warrensbox/terraform-switcher info installed /home/xat/.local/bin/tfswitch
```

Then, I am able to `tfswitch`, but there I need to use `-b` to define the complete location of the `terraform` symlink for the binary :

```
~/.local/bin/tfswitch -b ~/.local/bin/terraform 
2021/03/05 10:38:38 Creating directory for terraform: /home/xat/.terraform.versions/
✔ 0.14.7
Downloading https://releases.hashicorp.com/terraform/0.14.7/terraform_0.14.7_linux_amd64.zip to terraform_0.14.7_linux_amd64.zip
Downloading ...
33783879 bytes downloaded.
Switched terraform to version "0.14.7" 
```

Hope this help
