### ISSUE TITLE
Switching terraform version on M1 architecture Mac OS 11 (Big Sur) results in error

### ISSUE THREAD

**Issue by blugri** [warrensbox/terraform-switcher#132]
Running tfswitch on M1 architecture with MacOS 11 (Big Sur) does not work and reports the following error:

Error - Binary path does not exist: /usr/local/bin
Create binary path: /usr/local/bin for terraform installation

The terraform application is not installed.

**Comment by skyzyx** [comment]
I'm on Big Sur, and I don't have this issue.

**Comment by blugri** [comment]
@skyzyx Are you on the M1 chipset? I have the problem on M1.

**Comment by skyzyx** [comment]
Ah. I'm on x86. I think the M1 is context I didn't see in the original post.

Terraform doesn't have official releases for M1 yet. That's probably the problem.￼

**Comment by pckilgore** [comment]
Seems to be a permissions issue (which idk why that would be different between Big Sur arches), easy workaround seems to be to give `tfswitch` a user-owned directory (I add ~/bin as top item in PATH in my profile):

```
(✓) 19:06:30 [~/code/pckilgore/learn-terraform-circleci::master]
$ tfswitch
Reading required version from terraform file
Reading required version from constraint: > 1.0.0
Matched version: 1.0.1
2021/06/28 19:06:45
		Unable to create new symlink.
		Maybe symlink already exist. Try removing existing symlink manually.
		Try running "unlink /usr/local/bin/terraform" to remove existing symlink.
		If error persist, you may not have the permission to create a symlink at/usr/local/bin/terraform.
		Error: symlink /Users/patrick/.terraform.versions/terraform_1.0.1 /usr/local/bin/terraform: permission denied


(✖ - 1) 19:06:45 [~/code/pckilgore/xxx::master]
$ tfswitch -b ~/bin/terraform
Reading required version from terraform file
Reading required version from constraint: > 1.0.0
Matched version: 1.0.1
Switched terraform to version "1.0.1"

(✓) 19:06:53 [~/code/pckilgore/xxx::master]
$ which terraform
/Users/patrick/bin/terraform

(✓) 19:07:00 [~/code/pckilgore/xxx::master]
$ terraform -v
Terraform v1.0.1
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.44.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
```

Happy to help debug some more if you have ideas but the workaround is pretty easy.

**Comment by davehowell** [comment]
Looks like there are now M1 (arm) releases since 1.0.2 https://releases.hashicorp.com/terraform/1.0.2/terraform_1.0.2_darwin_arm64.zip

I've previously added `~/bin` to my `PATH` so I don't have any issue with this, as per https://github.com/warrensbox/terraform-switcher/issues/151 

I tried running `tfswitch` in another repo, which installed `1.0.4`. When I run `terraform -v` I can see it has installed the `amd64` binary, not the `arm64`. It doesn't matter; that `amd64` (x86_64) binary works just fine, but perhaps some point in the future it should pick the correct build for this architecture.

**Comment by matiasict** [comment]
I have the same problem. You can fix it like this:

```
cd /usr/local/
sudo mkdir bin
sudo chmod 777 bin
```

**Comment by skyzyx** [comment]
> I have the same problem. You can fix it like this:
> 
> ```
> cd /usr/local/
> sudo mkdir bin
> sudo chmod 777 bin
> ```

Nothing personal, but this is bad advice from a security angle.

If you find yourself setting directories to `0777`, then _something is wrong_. Check user and group associations before setting things (especially entire directories) to `0777`. Do you simply need to add your user to a particular group? On macOS, do you just need to add yourself to the `wheel` or `admin` group?
