### ISSUE TITLE
why are there files going into my homedir?

### ISSUE THREAD

**Issue by SvenDowideit** [warrensbox/terraform-switcher#133]
from the code, there are comments that say:

```
* 1- Create /usr/local/terraform directory if does not exist
* 2- Download zip file from url to /usr/local/terraform
* 3- Unzip the file to /usr/local/terraform
* 4- Rename the file from `terraform` to `terraform_version`
```

but the files are ending up in `/root/.terraform.versions` because I need to use `sudo ./terraform-switcher`, because my `/usr/local/bin` is not writeable by my user - and it should not be writeable by any user...

(I'm asking to find out if there was a good reason, or if a PR is warranted)

**Comment by maxbrunet** [comment]
I would guess that `tfswitch` was initially designed for MacOS where `/usr/local/bin` is writable (or is made so by Homebrew). On Linux, I change the path with the `--bin` flag:

```shell
tfswitch --bin="${HOME}/.local/bin/terraform"
```

(It would be nice if it was an environment variable in my shell profile)

In my opinion, `tfswitch` should not be run as root (unless maybe a system-wide setup, but the symlink remains awkward).

**Comment by SvenDowideit** [comment]
that's the thing - we use multi-user unix hosts. so there is no point at which we'd use this and its not system-wide.

**Comment by SvenDowideit** [comment]
I guess the real problem is - if you're installing into `/usr/local/bin` by default, then it should do the right thing for multi-user use

if you don't want to do multi-user, then the files should not be going there, and the user should need to setup their own PATH
