### ISSUE TITLE
Issue setting the right version in .tfswitch.toml file

### ISSUE THREAD

**Issue by oh-carlos-iglesias** [warrensbox/terraform-switcher#136]
Hi, this issue pops up a few versions back, 0.9.934 but is still present in the current 0.10.1010.
I have a .tfswitch.toml file with the following configuration:
`version = "0.12.29"`
Single line, no other chars in the file, simple and clean.

When I move into the directory tfswitch reads the file and switches to terraform version 0.12.30 with the following 
message:
`
Reading configuration from current directory for .tfswitch.toml
Reading required version from terraform file, constraint: ~> 0.12
Matched version: 0.12.30
Switched terraform to version "0.12.30" 
`

and a terraform version is effectively 0.12.30:
`$ terraform -v`
`Terraform v0.12.30`
`+ provider.aws v2.68.0`
`+ provider.local v2.1.0`
`+ provider.sops v0.5.2`
`+ provider.template v2.2.0`
`  `
`Your version of Terraform is out of date! The latest version is 0.14.7. You can update by downloading from https://www.terraform.io/downloads.html`

I can swap versions by hand without any trouble:
`$ tfswitch 0.12.29`
`Reading configuration from current directory for .tfswitch.toml`
`Switched terraform to version "0.12.29" `

Running Catalina 10.15.7

Any clue what could be the issue?

**Comment by warrensbox** [comment]
I am unable to reproduce this error. 
Please let me know if you are still seeing this error
