### ISSUE TITLE
latest-pre isn't picking up 0.15-beta1

### ISSUE THREAD

**Issue by skyzyx** [warrensbox/terraform-switcher#137]
Worked well with the alpha releases.

```bash
$ tfswitch --latest-pre 0.15
The provided terraform version format does not exist - . Try `tfswitch -l` to see all available versions.
```

```text
$ tfswitch -l
Use the arrow keys to navigate: ↓ ↑ → ←
? Select Terraform version:
  ▸ 0.14.7 *recent
    0.15.0-beta1
    0.15.0-alpha20210210
    0.15.0-alpha20210127
↓   0.15.0-alpha20210107
```

**Comment by warrensbox** [comment]
I will release this fix by next week! Thank you.

**Comment by warrensbox** [comment]
@skyzyx I fixed this bug
![pre-rel](https://user-images.githubusercontent.com/38867521/110507487-adef8400-80c5-11eb-8d06-0569ac20bf52.gif)
 Please get the latest version and verify if it's working as expected.
 https://tfswitch.warrensbox.com/Upgrade-or-Uninstall/
 Thanks!
