### ISSUE TITLE
should not require root or -b when switching

### ISSUE THREAD

**Issue by schollii** [warrensbox/terraform-switcher#151]
By default tfswitch assumes current user can write to /usr/local/bin. If this is not true, then you only have 2 options, neither of them are nice: 
1. every time you want to switch terraform version, you have to `sudo tfswitch` AND thereafter you have to `sudo terraform` because when you `sudo tfswitch` the location of terraform files ends up being root. You could of course do `sudo tfswitch -b /usr/local/bin/tfswitches` but then you would have to alias this in your .bashrc
2. every time you want to switch terraform version, you have to `tfswitch -b some/path/to/terraform` AND your `PATH` env var must contain `some/path/to`, which requires creating the folder, editing editing .bashrc to extend the path; and since no one wants to be entering the path everytime, you have to create an alias

It does not appear to be possible to use the .tfswitch.toml file to capture bin location as this requires a version (or applies only to the current version)

The default location of terraform should be the user's $HOME/bin. The `tfswitch` would just work with only the need to add $HOME/bin to path in .bashrc.

**Comment by amine250** [comment]
I couldn't agree more. 
There's no excuse to give root access to a tool that downloads a binary and symlinks into a given directory.

To my understanding, tfswitch was first developped for MacOS, and /usr/local/bin permissions in MacOS differ from linux's permissions. While the former is owned by the normal user, the latter is owned by root.

The difficulty here would be to find a directory that's in the PATH of most of OSs and that's also writable by the normal user.

**Comment by schollii** [comment]
@amine250
> find a directory that's in the PATH of most of OSs and that's also writable by the normal user.

The only one that satisfies this is user's home directory. 

That's really what should be the default anyways: rarely would every user of a system want to use the same version of terraform.

**Comment by warrensbox** [comment]
With the latest release, tfswitch will automatically attempt to use $HOME/bin. You don't need to use the `-b` option. 
Download the latest release (`>0.12.1168`)  to test it out. Please let me know if you find any bugs. Thanks.

```
1. For linux users that do not have write permission to `/usr/local/bin/`, `tfswitch` will attempt to install terraform at `$HOME/bin`. Run `export PATH=$PATH:$HOME/bin` to append bin to PATH  
2. For windows host, `tfswitch` need to be run under `Administrator` mode, and `$HOME/.tfswitch.toml` with `bin` must be defined (with a valid path) as minimum, below is an example for `$HOME/.tfswitch.toml` on windows
```

**Comment by amine250** [comment]
> With the latest release, tfswitch will automatically attempt to use $HOME/bin. You don't need to use the `-b` option.
> Download the latest release (`>0.12.1168`) to test it out. Please let me know if you find any bugs. Thanks.
> 
> ```
> 1. For linux users that do not have write permission to `/usr/local/bin/`, `tfswitch` will attempt to install terraform at `$HOME/bin`. Run `export PATH=$PATH:$HOME/bin` to append bin to PATH  
> 2. For windows host, `tfswitch` need to be run under `Administrator` mode, and `$HOME/.tfswitch.toml` with `bin` must be defined (with a valid path) as minimum, below is an example for `$HOME/.tfswitch.toml` on windows
> ```

Thanks, I'll try it out asap.
It should also be mentioned in the README that the $HOME/bin should be in the PATH (if it's not already mentioned).

**Comment by schollii** [comment]
I think `$HOME/.local/bin` is the standard location. See eg the answers in https://stackoverflow.com/questions/30274743/what-is-the-purpose-of-home-local.

**Comment by warrensbox** [comment]
@schollii Previously you suggested `$HOME/bin`. I assumed most people agreed with that suggestion.

>The default location of terraform should be the user's $HOME/bin. The tfswitch would just work with only the need to add $HOME/bin to path in .bashrc.

I was going off your initial suggestion. I do not mind `$HOME/.local/bin` 🙂
But let's see how many thumbs up you get from your new suggestion.

**Comment by yermulnik** [comment]
Basically `$HOME/.local` is the part of https://specifications.freedesktop.org/ specs which (`freedesktop.org`) is about `interoperability and shared technology for open-source graphical and desktop systems` but to **`CLI`**.

**Comment by schollii** [comment]
@warrensbox haha indeed I just didn't think of it at the time. Python uses it, and some other tools (helm plugins?). The  home/.local (and its bin subfolder in particular) was designed exactly for the subject of this ticket: so that in general your home folder doesn't end up with a pile of subfolders from user-specific app installs, such as bin, lib, share, etc. It is 100% not just for GUI.

**Comment by yermulnik** [comment]
@schollii JFYI: references to a community-driven **QA** web sources is kinda ridiculous to argue that `$HOME/.local/bin` is the **standard** location. This is the spec from GUI org.
Historically none of the unices et alii had it in the default user `PATH` (whilst `$HOME/bin` was (and still is there) there by default). Moreover based on the quick google search the only reason (back in 2018 — only three years ago) to request Ubuntu, CentOS, RedHat, etc to add `$HOME/.local/bin` to the default `PATH` was that at some point in time Python started to use it to install user local binaries.

What I mean is @warrensbox please keep `$HOME/bin` as default path for non-systemwide installations and (maybe but not necessary) add an option to change it to `$HOME/.local/bin` for those who prefer it over `~/bin`.

By the way, I just took a look into `$HOME/.local/bin` dir on two desktop systems (both are Ubuntu-based) which are used very often (my work station and my home station) and these two dirs have Python binaries *only* — kinda user local home for Python bins only. Whereas none of non-desktop systems I have access to have `$HOME/.local/bin` in there at all.

Though to obey equality I must admit that **some** CLI tools indeed use `$HOME/.local/share` to persist user-specific **dynamic** data whilst **most** of CLI tools use other locations.

**Comment by yermulnik** [comment]
> and some other tools (helm plugins?)

```
> helm env HELM_PLUGINS
/home/giermulnik/.local/share/helm/plugins
```

**Comment by schollii** [comment]
@yermulnik about helm exactly, as you see helm uses home/.local as the base, this folder is the user-specific equivalent of /usr and /usr/local, and its plugins go in share so home/.local/share.

If you look at those posts, the trend is to move away from home as the root for user-specific bin, share, lib etc, in favor of home/.local. So the default for terraform switcher binary should be home/.local/bin, and if it has a config file, it should be somewhere under home/.local like home/.local/etc or home/.local/var. 

But home/bin is not the only alternative, so the user needs to have the ability to choose whatever else as root (home, /usr/local, etc). If user selects home as root then installation script would create it in home/bin. 

Summary: 
- home/.local as root folder is the future, so it should be the default in which to put bin
- allow to override the default root folder with any path, then the install will create bin in there

**Comment by yermulnik** [comment]
> as you see helm uses home/.local as the base

No, it does not use `$HOME/.local` as the base. Or at least not the way you tend to interpret it. Running `helm env` would let us see that `$HOME/.local` used to store DATA and PLUGINS (and even plugins' executable files are not placed into `$HOME/.local/bin`).

`helm` tries its best to conform to [`XDG Base Directory Specification`](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) (freedesktop.org) which among other statements specifies that `User-specific executable files may be stored in $HOME/.local/bin` and the "**may**" here is not equal to "**should**" or "**must**".

And I'd like to emphasize once again: the **main** (if not the only) user of `$HOME/.local/bin` is Python (as per [PEP-370](https://www.python.org/dev/peps/pep-0370/) it was chosen `because the directory is already used by several other programs in analogy to /usr/local`).

Also we should keep in mind that `dot-files` mostly are the hidden files. Not sure why would `tfswitch` want to hide itself from the user.

**Comment by schollii** [comment]
Well this says it all: 

> because the directory is already used by several other programs in analogy to /usr/local". 

So the Python authors were just making that up, they were actually the first? 

In any case, let's keep in mind the primary objective of this issue: to allow the user of tfswitcher to choose the location of terraform binaries. The *default* location is merely a convenience, so that if it matches what user wants, they have one less thing to specify on command line, as env variable, or in config file. To be clear, end-user of tfswitcher should not have to specify the location every time they switch terraform version, so their choice (different from the default) needs to be in an env var or a config file.

**Comment by yermulnik** [comment]
> So the Python authors were just making that up

Nope. This is not Python but XDG spec. Spec for GUI not CLI.
Among mostly `should be`-dirs the `$HOME/.local/bin` is the `may be`-dir. Which means it is the instance of _optional_ among those which _should be_ used.

> they were actually the first?

They are actually the only ones.

> The default location is merely a convenience

Absolutely! This is why I vouch for `$HOME/bin` as a more commonly and widely used path rather than `$HOME/.local/bin`.

**Comment by davehowell** [comment]
> > With the latest release, tfswitch will automatically attempt to use $HOME/bin. You don't need to use the `-b` option.
> > Download the latest release (`>0.12.1168`) to test it out. Please let me know if you find any bugs. Thanks.
> > ```
> > 1. For linux users that do not have write permission to `/usr/local/bin/`, `tfswitch` will attempt to install terraform at `$HOME/bin`. Run `export PATH=$PATH:$HOME/bin` to append bin to PATH  
> > 2. For windows host, `tfswitch` need to be run under `Administrator` mode, and `$HOME/.tfswitch.toml` with `bin` must be defined (with a valid path) as minimum, below is an example for `$HOME/.tfswitch.toml` on windows
> > ```
> 
> Thanks, I'll try it out asap.
> It should also be mentioned in the README that the $HOME/bin should be in the PATH (if it's not already mentioned).

`$HOME/bin` makes total sense, I just want to add that I am setting up a new Big Sur machine and `$HOME/bin` is not part of the default `$PATH`. I thought that was a bit odd, but I can't remember if it was like that on previous OSX versions. 

I've not heard of `$HOME/.local/bin`, but the same would apply, you'd have to explicitly add it to the path. Of the choices I have to agree that `$HOME/bin` is the least surprising.

**Comment by warrensbox** [comment]
Release >0.12.1168 should fix this. 
 I am closing this issue to focus on other issues
