### ISSUE TITLE
Unable to download terraform 

### ISSUE THREAD

**Issue by vusonhust** [warrensbox/terraform-switcher#152]
```
✔ 0.14.8
Downloading https://releases.hashicorp.com/terraform/0.14.8/terraform_0.14.8_darwin_arm64.zip to terraform_0.14.8_darwin_arm64.zip
Downloading ...
Unable to download from https://releases.hashicorp.com/terraform/0.14.8/terraform_0.14.8_darwin_arm64.zip
Please download manually from https://releases.hashicorp.com/terraform/
```
if I visit direct download link in browser, 403 Forbidden error appear, but if I browse `https://releases.hashicorp.com/terraform/0.14.8/` then click file to download, I can download it. 

(For reference, I'm using M1 Macbook Pro)

**Comment by lordz-md** [comment]
Same issue here.

**Comment by warrensbox** [comment]
@vusonhust and @lordz-md  what version of `tfswitch -v` do you have?

**Comment by vusonhust** [comment]
@warrensbox my version is 0.11.1071

**Comment by benbieler** [comment]
same problem with a M1 mac

**Comment by ElAouaneHamza** [comment]
I have the same problem. I am on a MacBook Air m1. Did anyone find a solution to this?

**Comment by ElAouaneHamza** [comment]
the download link is wrong. is pointing to amd64 but online there is only the version arm64

**Comment by warrensbox** [comment]
I am in the process of debugging this.
@ElAouaneHamza 
>the download link is wrong. is pointing to amd64 but online there is only the version arm64

Where do you see that the download link is pointing to the wrong amd64

**Comment by mperklin** [comment]
```
tfswitch -u
Downloading https://releases.hashicorp.com/terraform/0.14.9/terraform_0.14.9_darwin_arm64.zip to terraform_0.14.9_darwin_arm64.zip
Downloading ...
Unable to download from https://releases.hashicorp.com/terraform/0.14.9/terraform_0.14.9_darwin_arm64.zip
Please download manually from https://releases.hashicorp.com/terraform/
```

The M1 runs `darwin_arm64`, but when you look at [https://releases.hashicorp.com/terraform/0.14.9/](https://releases.hashicorp.com/terraform/0.14.9/) there is no `darwin_arm64`. There's only `darwin_amd64`.

Hashicorp needs to post their arm64 binaries at that path.

In the meantime, I wonder if this can run with Rosetta

**Comment by warrensbox** [comment]
@mperklin Thank you for clarifying. I don't have a M1 system to test this. Until [AWS comes up with a system that I can use to test my application](https://www.zdnet.com/article/aws-offers-mac-ec2-instances-here-what-it-means-for-apple/)), I have to rely on other to test this . But your clarification  certainly saved a lot of debugging time.

**Comment by vusonhust** [comment]
This work normally when using iterm 2 in rosetta mode. I think on Mac ARM we can set download to use amd64 link since there is no version for Mac ARM right now

**Comment by chrispruitt** [comment]
i didn't look too deep into this, but anyone looking for a quick and dirty fix, this is working for me
https://github.com/chrispruitt/terraform-switcher

**Comment by warrensbox** [comment]
@chrispruitt can you please create a merge request with your change. I think the most significant lines are on this file:
 lib/install.go (lines 94-98)
 ```
 	// TODO: Workaround for macos arm64 since terraform doesn't have a binary for it yet
	if goos == "darwin" && goarch == "arm64" {
		goarch = "amd64"
	}
```
I can merge your request and release the fix. I would certainly appreciate the help.

**Comment by warrensbox** [comment]
Thank you @chrispruitt. I will test and merge it after testing.

**Comment by chrispruitt** [comment]
Happy to help @warrensbox and thanks for the awesome tool. I use it daily.
