### ISSUE TITLE
The amd64 precompiled binary doesn't work on Alpine

### ISSUE THREAD

**Issue by amine250** [warrensbox/terraform-switcher#155]
Hi,

The precompiled binary for linux amd64 doesn't work on Alpine docker images.
It seems that it needs to be compiled with the command `CGO_ENABLED=0 go build` to not having it depend on `glibc` which is substitued by `musl` in Alpine.

**Comment by warrensbox** [comment]
@amine250 can you test this binary on your alpine box?
https://github.com/warrensbox/terraform-switcher/releases/tag/0.11.1071

download: terraform-switcher_0.11.1071_alpine_arm64

Please let me know if that works.

**Comment by MatrixCrawler** [comment]
Cannot reproduce this issue

![image](https://github.com/warrensbox/terraform-switcher/assets/5767285/768aa3d8-d17d-49f1-8221-936d932ddfec)
