### ISSUE TITLE
put terraform symlink into the directory of tfswitch itself

### ISSUE THREAD

**Issue by toralf** [warrensbox/terraform-switcher#156]
Would help to not weaken the permissions of the /usr/local/bin directory + does not need the -b switch ;)

**Comment by toralf** [comment]
BTW the install script mention that BINDIR is set to "./bin" but it is rather /usr/local/bin, or?
And -b needs to be the complete symlink file name, not only the dir where the symlink resides, or ?

**Comment by MatrixCrawler** [comment]
Do you mean to change the default behaviour?
With the -b/--bin parameter, which would be the full path to the symlink created, you could always choose the target for the symlink.

**Comment by toralf** [comment]
pffrr - report was 3 yrs ago 

Currently I put terraform into the $HOME/bin directory rather than in /usr/local/bin, where only root is allowed to write into it. This works well.
