### ISSUE TITLE
RFE: tfswitch should exit with an error if the syntax in .tfswitchrc is not correct

### ISSUE THREAD

**Issue by toralf** [warrensbox/terraform-switcher#159]
currently it returns 0 in such a case.

**Comment by warrensbox** [comment]
I'm working on this. Thanks for bringing this up!

**Comment by warrensbox** [comment]
This is issue is fixed with release 0.12.1092
Release #163
Please upgrade and verify:
https://tfswitch.warrensbox.com/Upgrade-or-Uninstall/

**Comment by toralf** [comment]
fixed - thx
