### ISSUE TITLE
error creating terraform version permission denied

### ISSUE THREAD

**Issue by dq-peytz** [warrensbox/terraform-switcher#173]
I install the tf switch with snap on a Ubuntu foca and got this error:

![image](https://user-images.githubusercontent.com/84777812/119982864-ac947000-bfbf-11eb-80f2-bc74dcc7c61c.png)

**Comment by yermulnik** [comment]
I'd assume the following commands can help investigating your issue:
```
whoami
ls -ld /home/diego/ /home/diego/.terraform.versions/
lsattr -d /home/diego/ /home/diego/.terraform.versions/
```

**Comment by sjshuck-fpco** [comment]
I think this might be related to it being installed via Snap.
If you install it via `snap install --classic` does the problem persist?

**Comment by warrensbox** [comment]
I am trying to resolve this issue with snapcraft. I'm requesting additional permission here :
https://forum.snapcraft.io/t/request-interface-personal-files-read-write/25277/2
If you have a snapcraft account, please vote for this issue

**Comment by warrensbox** [comment]
Snapcraft is no longer supported.
Please use other installation methods
