### ISSUE TITLE
terragrunt.hcl file without any constraints causes tfswitch to fail

### ISSUE THREAD

**Issue by amirtal-cp** [warrensbox/terraform-switcher#181]
running tfwsitch in a folder with terragrunt.hcl files without any version constraints returns an error:

```
❯ tfswitch -v

Version: 0.12.1119
❯ touch terragrunt.hcl
❯ cat terragrunt.hcl
❯ tfswitch
Terragrunt file found: /tmp/terragrunt.hcl
Reading required version from constraint:
Error parsing constraint: improper constraint:
Please check constrain syntax on terraform file.
```

**Comment by warrensbox** [comment]
@amirtal-cp `brew upgrade warrensbox/tap/tfswitch` 
Thanks for opening this issue. The latest release should fix this

**Comment by amirtal-cp** [comment]
> @amirtal-cp `brew upgrade warrensbox/tap/tfswitch`
> Thanks for opening this issue. The latest release should fix this
> Please test and let me know!

confirmed.
thanks!
