### ISSUE TITLE
Update Golang Package Version on pkg.go

### ISSUE THREAD

**Issue by xavipanda** [warrensbox/terraform-switcher#192]
Actually a very old version is in there and miss most of the existing functions, would be nice to get this updated in the pkg.go repo

**Comment by warrensbox** [comment]
Please elaborate

**Comment by psihachina** [comment]
Hi, @warrensbox 

In pkg.go [terraform-switcher](https://pkg.go.dev/github.com/warrensbox/terraform-switcher@v0.1.0) is not updated due to the [version tag](https://github.com/golang/go/wiki/Modules#modules). The version tag must contain the letter "v". It would be great if you fixed this, then me and anyone else could use your package in other projects.

**Comment by leosunmo** [comment]
This is currently biting me as well. Go is unaware of anything newer than `v0.1.0` as seen in https://pkg.go.dev/github.com/warrensbox/terraform-switcher

**Comment by MatrixCrawler** [comment]
See https://pkg.go.dev/about#adding-a-package

> Data for the site is downloaded from [proxy.golang.org](https://proxy.golang.org/). We monitor the [Go Module Index](https://index.golang.org/index) regularly for new packages to add to pkg.go.dev. If you don’t see a package on pkg.go.dev, you can add it by doing one of the following:
> 
> - Visiting that page on pkg.go.dev, and clicking the “Request” button. For example: https://pkg.go.dev/example.com/my/module
> 
> - Making a request to proxy.golang.org for the module version, to any endpoint specified by the [Module proxy protocol](https://pkg.go.dev/cmd/go/#hdr-Module_proxy_protocol). For example:
> https://proxy.golang.org/example.com/my/module/@v/v1.0.0.info
> 
> - Downloading the package via the [go command](https://pkg.go.dev/cmd/go/#hdr-Add_dependencies_to_current_module_and_install_them). For example:
> GOPROXY=https://proxy.golang.org GO111MODULE=on go get example.com/my/module@v1.0.0

As i understand a request to https://proxy.golang.org/example.com/my/module/@v/v1.0.0.info on release should do the trick?

**Comment by MatrixCrawler** [comment]
Here is a description how to add it to github actions (pretty far down the page)
https://forcepush.tech/go-package-ci-cd-with-git-hub-actions

**Comment by yermulnik** [comment]
@MatrixCrawler I've added my thoughts to #354 — lety's get hold of @warrensbox to discuss this "feature".
