### ISSUE TITLE
Add options to just show a version rather than install and switch to it

### ISSUE THREAD

**Issue by grimm26** [warrensbox/terraform-switcher#194]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to have tfswitch tell me what the latest/stable/pre version is before I choose to actually install it.

**Describe the solution you'd like**
I'm adding complementary "show" options to the three "latest" options that currently exist.
- --show-latest-pre
- --show-latest-stable
- --show-latest

PR ready: https://github.com/warrensbox/terraform-switcher/pull/193

**Comment by MatrixCrawler** [comment]
Solved with #193

**Comment by yermulnik** [comment]
Odd is that PR doesn't seem to work for me — any of the three options just bring up a `? Select Terraform version:` menu for me 😲 (I'm on version `1.0.2`). Does any of those three options work for anyone?

**Comment by MatrixCrawler** [comment]
Oh I never actually tested that 🫣
I just saw that this option was introduced with the pr and thought this was just left open accidentally

**Comment by MatrixCrawler** [comment]
It is working for me as expected

![image](https://github.com/warrensbox/terraform-switcher/assets/5767285/b65aaa72-4d54-4672-bf28-6a4a15ceba90)
