### ISSUE TITLE
warrensbox/terraform-switcher crit platform linux/arm64 is not supported.

### ISSUE THREAD

**Issue by AndreasPrang** [warrensbox/terraform-switcher#197]
**Is your feature request related to a problem? Please describe.**
I try to install terraform-switcher in Docker xbuild to generate a arm64 & amd64 image. In the linux/arm64 build I ge this error.

**Describe the solution you'd like**
Not sure what's the issue in the script. Did you miss to whitelist the artefact?
⇨ https://github.com/warrensbox/terraform-switcher/pull/198

** Installation process
  curl -L https://raw.githubusercontent.com/warrensbox/terraform-switcher/release/install.sh | bash

**Comment by AndreasPrang** [comment]
#52 5.954 install warrensbox/terraform-switcher
#52 5.959   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
#52 5.959                                  Dload  Upload   Total   Spent    Left  Speed
100  9187  100  9187    0     0  30220      0 --:--:-- --:--:-- --:--:-- 30220
#52 6.292 warrensbox/terraform-switcher info checking GitHub for latest tag
#52 6.682 warrensbox/terraform-switcher info found version: 0.12.1168 for 0.12.1168/linux/arm64
#52 8.009 warrensbox/terraform-switcher info installed /usr/local/bin/tfswitch

**Comment by kral2** [comment]
I can confirm that just downloading the source from [latest release](https://github.com/warrensbox/terraform-switcher/releases/download/0.12.1168/terraform-switcher_0.12.1168_linux_arm64.tar.gz) and extracting the archive is enough to have it working on a linux/arm64 operating system.

Successfully tested on Oracle Linux 8.4  running on arm64.

It seems we just need to add arm64 as a valid platform on the install script checks, which is exactly what PR #198 does 👍

**Comment by warrensbox** [comment]
Fixed #206 and #198

**Comment by apaziuk** [comment]
1. Download the archive from [](https://github.com/warrensbox/terraform-switcher/releases).
2. tar xvf terraform-switcher_0.13.1308_linux_amd64.tar.gz (I am using 0.13 version)
3. Go to Donwloads folder and execute `sudo mv tfswitch /usr/local/bin`
