### ISSUE TITLE
SemVer issue with Terraform on v1 releases

### ISSUE THREAD

**Issue by stevehipwell** [warrensbox/terraform-switcher#200]
I ran the following command and got an error despite it being semantically the same as the documented `tfswitch --latest-stable 0.13` command.

```shell
$ tfswitch --latest-stable 1
$ Invalid minor terraform version format. Format should be #.# where # are numbers. For example, 0.11 is valid version
```

I suspect this is because this tool was only designed to work with pre v1 versions of Terraform. Semantically in `v0.11` there is no explicit minor version as the major version is `11`.

**Comment by warrensbox** [comment]
@stevehipwell 

At this time, `tfswitch --latest-stable 0.11` downloads the latest stable version for V0.11.
`tfswitch --latest-stable 1.0` should download the latest stable version for V1.0.

Just to clarify are you saying that `tfswitch --latest-stable 1` should download the latest stable version for V1.0 ?

**Comment by warrensbox** [comment]
@yermulnik @stevehipwell I was looking at the docs. 
`--latest-stable 1` should mimic `~> 1`.  
```
terraform {
  required_version = "~> 1"

  required_providers {
    aws        = ">= 2.52.0"
    kubernetes = ">= 1.11.1"
  }
}
```
The code above downloads 1.14 (latest at this time).
I need to make changes to the code to allow `tfswitch --latest-stable 1` to download  1.14 (latest at this time).

**Comment by yermulnik** [comment]
@warrensbox Just for the sake of clarity: latest is `1.1.4`

**Comment by warrensbox** [comment]
> 



> @warrensbox Just for the sake of clarity: latest is `1.1.4`

Yes. that's what I meant. That's a typo.

**Comment by warrensbox** [comment]
#216 fixed
