### ISSUE TITLE
command not found: terraform

### ISSUE THREAD

**Issue by codafett** [warrensbox/terraform-switcher#203]
Env: Mac Book Pro M1 chip
Term: iTerm using zsh

I installed terraform via howbrew.

I'm able to run ```terraform -help``` and list out help commands.

I installed tfswitch via homebrew.

If I run ```terraform -help``` now I get ```zsh: command not found: terraform```

I can run tfswitch and switch to a different version of terraform but running ```terraform -help``` results in the same error.

The only work around I can find is to run ```brew unlink terraform``` and then ```brew link terraform``` to get the command line to recognise the terraform command, however, this then reverts to the latest version of terraform?

**Comment by galvo-bowers** [comment]
So i had this problem.
I resolved it.

Look where TFSWITCH is putting the Terraform Binary.

Instead of putting it in the Homebrew bin it was putting it in /Users/Me/bin

i just added that bin directory to my path. and it works just fine. 

Should note that i didnt install terraform via brew, i just let tfswitch do it

**Comment by yermulnik** [comment]
`tfswitch` has nothing to do with `Homebrew` and `Homebrew`'s bin path.
It seems to me that `tfswitch` uses `/usr/local/bin` by default (https://github.com/warrensbox/terraform-switcher/blob/master/main.go#L48) whereas `/usr/local/bin` might not be a part of the `PATH` env var be default on MacOS (I might be wrong though).
You can check the contents of `PATH` env var by running `echo $PATH` command in your terminal. And if `/usr/local/bin` is not there, just append it to the `PATH` env var (pay attention that you need to use a correct separator of `:`).
If you use Bash you can simply add the below line to your `.bashrc` and reload it or re-login:
```
export PATH="${PATH+$PATH:}/usr/local/bin"
```

**Comment by codafett** [comment]
Thanks for the replies, /usr/local/bin was already in my $PATH and I can see that tfswitch is downloading to /Users/Me/bin so that seems to make sense. Annoyingly having retried it just now it seems to be working without having changed anything - so maybe it just lost config somewhere and sorted itself. I know someone else I worked with was having a similar issue so I'll check with them to see if these help fix it.

thanks again!!

**Comment by yermulnik** [comment]
Do you have `.tfswitch.toml` in your home dir with custom bin path set in it as per https://github.com/warrensbox/terraform-switcher#use-tfswitchtoml-file--for-non-admin---users-with-limited-privilege-on-their-computers ?
This is the only option I can imagine for `tfswitch` to use non-default bin path (apart from explicitly specifying `-b` or `--bin` parameter in the command line).

**Comment by rafayely** [comment]
Same for me on a M1 MacBook Pro. Tfswitch is downloading to /Users/Me/bin.
