### ISSUE TITLE
tfswitch should really install the right terraform architecture binaries on OSX M1

### ISSUE THREAD

**Issue by gtmtech** [warrensbox/terraform-switcher#204]
When running `tfswitch install` on OSX M1, terraform is installed, however the x86_64 version is installed. 
This was acceptable when terraform had only non-arm binaries, but now that it does, it means all OSX people are getting versions which have to be emulated, occasionally crash, and also are a lot slower.

**Describe the solution you'd like**

I want tfswitch install to install the arm64 binaries from the terraform downloads if the underlying arch is darwin arm64/aarch64

**Describe alternatives you've considered**

The alternatives are basically to use other tools, or hack my own download over the top of tfswitch, but then why use tfswitch.

**Additional context**

Terraform has now built arm64 binaries, so its much better and faster to use them

I believe there are only 3 lines which need deleting looking at the codebase for this to now work as planned (the logic in install.go which detects darwin/arm64 and then overrides the binary back to amd64

**Comment by gtmtech** [comment]
I see https://github.com/warrensbox/terraform-switcher/pull/202 has already been done but not merged. In fact a lot of unmerged easy PRs - is this repo still active?

**Comment by warrensbox** [comment]
see #206
