### ISSUE TITLE
Unable to install due to "Invalid formula" error

### ISSUE THREAD

**Issue by mantorok1** [warrensbox/terraform-switcher#214]
When I attempt to install tfswitch for the first time I'm getting several "Invalid formula" errors. Here's the output:
```
> brew install warrensbox/tap/tfswitch

==> Tapping warrensbox/tap
Cloning into '/usr/local/Homebrew/Library/Taps/warrensbox/homebrew-tap'...
remote: Enumerating objects: 549, done.
remote: Counting objects: 100% (107/107), done.
remote: Compressing objects: 100% (106/106), done.
remote: Total 549 (delta 49), reused 5 (delta 1), pack-reused 442
Receiving objects: 100% (549/549), 69.88 KiB | 2.79 MiB/s, done.
Resolving deltas: 100% (251/251), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/warrensbox/homebrew-tap/Formula/jscheck.rb
jscheck: Calling bottle :unneeded is disabled! There is no replacement.
Please report this issue to the warrensbox/tap tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/warrensbox/homebrew-tap/Formula/jscheck.rb:6

Error: Invalid formula: /usr/local/Homebrew/Library/Taps/warrensbox/homebrew-tap/Formula/hubapp.rb
hubapp: Calling bottle :unneeded is disabled! There is no replacement.
Please report this issue to the warrensbox/tap tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/warrensbox/homebrew-tap/Formula/hubapp.rb:9

Error: Invalid formula: /usr/local/Homebrew/Library/Taps/warrensbox/homebrew-tap/Formula/health-check.rb
health-check: Calling bottle :unneeded is disabled! There is no replacement.
Please report this issue to the warrensbox/tap tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/warrensbox/homebrew-tap/Formula/health-check.rb:9

Error: Cannot tap warrensbox/tap: invalid syntax in tap!
```

This might be related to Issue [#201](https://github.com/warrensbox/terraform-switcher/issues/201)

My environment:
- macOS version: `12.2.1`
- brew version: `Homebrew 3.3.16-64-g103cd0c`

Let me know if you need any further details.

**Comment by juniperalcorn** [comment]
Hi I am having the exact same problem! 
- brew: `Homebrew 3.4.0`
- maxOS `10.15.7`

**Comment by Mothirajha** [comment]
Hey Iam also facing the same problem! any work around to fix it

- brew: `Homebrew 3.4.0`

- macOS: `12.0.1`

**Comment by juniperalcorn** [comment]
I succesfully used the `curl` option [from the docs](https://tfswitch.warrensbox.com/Install/).

**Comment by sistella** [comment]
Same here:
- MacOS `12.2.1`
- brew `Homebrew 3.4.0`

the curl doesn't work for me

**Comment by Mothirajha** [comment]
Thank you @juniperalcorn

Tried with `curl` got permission issue, worked fine with wget from [trouble shoot docs](https://tfswitch.warrensbox.com/Troubleshoot/).

**Comment by hopkinsnji** [comment]
Experiencing the same problem when installing with brew. It worked with `curl`

`curl -L https://raw.githubusercontent.com/warrensbox/terraform-switcher/release/install.sh | bash
`

**Comment by jessmchung** [comment]
Same issue with `brew install warrensbox/tap/tfswitch`, haven't tried curl.

* MacOS `11.6.4`
* brew `Homebrew 3.4.0 Homebrew/homebrew-core (git revision 7e35b54d72d; last commit 2022-03-03)`

**Comment by marcoslhc** [comment]
The manual installation from the troubleshoot section worked for me

* Intel Mac (not ARM)
* MacOS Monterrey 12.2.1 (21D62)
* Homebrew 3.4.0
* Homebrew/homebrew-core (git revision 49fa997cd7f; last commit 2022-03-04)
* Homebrew/homebrew-cask (git revision fe09f6227a; last commit 2022-03-04)

```sh
wget https://raw.githubusercontent.com/warrensbox/terraform-switcher/release/install.sh
chmod 755 install.sh
mkdir /usr/local/tfswitch # create installation directory
./install.sh -b /usr/local/tfswitch # link in a "common" bin path (same used by Homebrew)
ln -s /usr/local/tfswitch/tfswitch /usr/local/bin/tfswitch # alternatively, add /usr/local/tfswitch to $PATH \ 
                                                           # export $PATH=$PATH:/usr/local/tfswitch/
                                                           # as recommended, you should add this to .zshrc
tfswitch # test
```

**Comment by warrensbox** [comment]
I've tested on:
MacOS : `12.2.1` 
```sh
➜  ~ brew --version
Homebrew 3.4.0
Homebrew/homebrew-core (git revision 83f6263b8cb; last commit 2022-03-06)
Homebrew/homebrew-cask (git revision fb78416166; last commit 2022-03-07)
```
I had to run:
```sh
xcode-select --install
```
Update brew:
```sh
brew update
```
Reinstall the tap:
```sh
 brew uninstall warrensbox/tap/tfswitch
 brew install warrensbox/tap/tfswitch
```
@marcoslhc are you using an Intel Mac or ARM. Please [check](https://support.apple.com/en-in/HT203001)  and let me know.

**Comment by m0ps** [comment]
I've tested on macOS 12.2.1 on MacBook Pro 16" M1 Pro CPU
The issue still exists:
```
Homebrew 3.4.0
Homebrew/homebrew-core (git revision 4912b7df9fc; last commit 2022-03-07)
Homebrew/homebrew-cask (git revision 08e6285a04; last commit 2022-03-07)
```
```
brew install warrensbox/tap/tfswitch
==> Tapping warrensbox/tap
Cloning into '/opt/homebrew/Library/Taps/warrensbox/homebrew-tap'...
remote: Enumerating objects: 549, done.
remote: Counting objects: 100% (107/107), done.
remote: Compressing objects: 100% (106/106), done.
remote: Total 549 (delta 49), reused 5 (delta 1), pack-reused 442
Receiving objects: 100% (549/549), 69.88 KiB | 5.38 MiB/s, done.
Resolving deltas: 100% (251/251), done.
Error: Invalid formula: /opt/homebrew/Library/Taps/warrensbox/homebrew-tap/Formula/jscheck.rb
jscheck: Calling bottle :unneeded is disabled! There is no replacement.
Please report this issue to the warrensbox/tap tap (not Homebrew/brew or Homebrew/core):
  /opt/homebrew/Library/Taps/warrensbox/homebrew-tap/Formula/jscheck.rb:6

Error: Invalid formula: /opt/homebrew/Library/Taps/warrensbox/homebrew-tap/Formula/hubapp.rb
hubapp: Calling bottle :unneeded is disabled! There is no replacement.
Please report this issue to the warrensbox/tap tap (not Homebrew/brew or Homebrew/core):
  /opt/homebrew/Library/Taps/warrensbox/homebrew-tap/Formula/hubapp.rb:9

Error: Invalid formula: /opt/homebrew/Library/Taps/warrensbox/homebrew-tap/Formula/health-check.rb
health-check: Calling bottle :unneeded is disabled! There is no replacement.
Please report this issue to the warrensbox/tap tap (not Homebrew/brew or Homebrew/core):
  /opt/homebrew/Library/Taps/warrensbox/homebrew-tap/Formula/health-check.rb:9

Error: Cannot tap warrensbox/tap: invalid syntax in tap!
```

**Comment by jochenhebbrecht** [comment]
I have exactly the same issue, I'm also on OS X 12.2.1 on a MacBook Pro 16" M1 machine

**Comment by Priyadarshi-Kumar** [comment]
I solved this issue on Macos running on M1 with following commands:

curl -L https://raw.githubusercontent.com/warrensbox/terraform-switcher/release/install.sh -o ./install.sh  
chmod +x install.sh 
sudo ./install.sh

**Comment by m0ps** [comment]
@Priyadarshi-Kumar you installed it via tarball (manual install). The issue is with installation via brew (packet manager).

**Comment by attachmentgenie** [comment]
@warrensbox i can reproduce the broken behaviour by running the following

```
~ ❯ brew uninstall tfswitch
Uninstalling /usr/local/Cellar/tfswitch/0.13.1201... (5 files, 10.0MB)
~ ❯ brew untap warrensbox/tap
Untapping warrensbox/tap...
Untapped 11 formulae (36 files, 107.8KB).
~ ❯ brew install warrensbox/tap/tfswitch
Running `brew update --preinstall`...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> New Formulae
mu-repo
==> Updated Formulae
Updated 2 formulae.

==> Tapping warrensbox/tap
Cloning into '/usr/local/Homebrew/Library/Taps/warrensbox/homebrew-tap'...
remote: Enumerating objects: 549, done.
remote: Counting objects: 100% (107/107), done.
remote: Compressing objects: 100% (106/106), done.
remote: Total 549 (delta 49), reused 5 (delta 1), pack-reused 442
Receiving objects: 100% (549/549), 69.88 KiB | 2.18 MiB/s, done.
Resolving deltas: 100% (251/251), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/warrensbox/homebrew-tap/Formula/jscheck.rb
jscheck: Calling bottle :unneeded is disabled! There is no replacement.
Please report this issue to the warrensbox/tap tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/warrensbox/homebrew-tap/Formula/jscheck.rb:6

Error: Invalid formula: /usr/local/Homebrew/Library/Taps/warrensbox/homebrew-tap/Formula/hubapp.rb
hubapp: Calling bottle :unneeded is disabled! There is no replacement.
Please report this issue to the warrensbox/tap tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/warrensbox/homebrew-tap/Formula/hubapp.rb:9

Error: Invalid formula: /usr/local/Homebrew/Library/Taps/warrensbox/homebrew-tap/Formula/health-check.rb
health-check: Calling bottle :unneeded is disabled! There is no replacement.
Please report this issue to the warrensbox/tap tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/warrensbox/homebrew-tap/Formula/health-check.rb:9

Error: Cannot tap warrensbox/tap: invalid syntax in tap!
```

**Comment by piscue** [comment]
> @warrensbox i can reproduce the broken behaviour by running the following
> 
> ```
> ~ ❯ brew uninstall tfswitch
> Uninstalling /usr/local/Cellar/tfswitch/0.13.1201... (5 files, 10.0MB)
> ~ ❯ brew untap warrensbox/tap
> Untapping warrensbox/tap...
> Untapped 11 formulae (36 files, 107.8KB).
> ~ ❯ brew install warrensbox/tap/tfswitch
> Running `brew update --preinstall`...
> ==> Auto-updated Homebrew!
> Updated 1 tap (homebrew/core).
> ==> New Formulae
> mu-repo
> ==> Updated Formulae
> Updated 2 formulae.
> 
> ==> Tapping warrensbox/tap
> Cloning into '/usr/local/Homebrew/Library/Taps/warrensbox/homebrew-tap'...
> remote: Enumerating objects: 549, done.
> remote: Counting objects: 100% (107/107), done.
> remote: Compressing objects: 100% (106/106), done.
> remote: Total 549 (delta 49), reused 5 (delta 1), pack-reused 442
> Receiving objects: 100% (549/549), 69.88 KiB | 2.18 MiB/s, done.
> Resolving deltas: 100% (251/251), done.
> Error: Invalid formula: /usr/local/Homebrew/Library/Taps/warrensbox/homebrew-tap/Formula/jscheck.rb
> jscheck: Calling bottle :unneeded is disabled! There is no replacement.
> Please report this issue to the warrensbox/tap tap (not Homebrew/brew or Homebrew/core):
>   /usr/local/Homebrew/Library/Taps/warrensbox/homebrew-tap/Formula/jscheck.rb:6
> 
> Error: Invalid formula: /usr/local/Homebrew/Library/Taps/warrensbox/homebrew-tap/Formula/hubapp.rb
> hubapp: Calling bottle :unneeded is disabled! There is no replacement.
> Please report this issue to the warrensbox/tap tap (not Homebrew/brew or Homebrew/core):
>   /usr/local/Homebrew/Library/Taps/warrensbox/homebrew-tap/Formula/hubapp.rb:9
> 
> Error: Invalid formula: /usr/local/Homebrew/Library/Taps/warrensbox/homebrew-tap/Formula/health-check.rb
> health-check: Calling bottle :unneeded is disabled! There is no replacement.
> Please report this issue to the warrensbox/tap tap (not Homebrew/brew or Homebrew/core):
>   /usr/local/Homebrew/Library/Taps/warrensbox/homebrew-tap/Formula/health-check.rb:9
> 
> Error: Cannot tap warrensbox/tap: invalid syntax in tap!
> ```

Exactly the same behavior from my side.

**Comment by Jean-Gualbert** [comment]
Hello,
I retried today, it’s work now.
Thank for the fix.

**Comment by piscue** [comment]
Same, thanks for the fix

**Comment by JochenHebbrecht-TomTom** [comment]
Fixed for me as well 👍

**Comment by jochenhebbrecht** [comment]
Fixed for me as well 👍

**Comment by mantorok1** [comment]
It's fixed for me too so I'm closing this issue
