### ISSUE TITLE
`terraform: command not found`

### ISSUE THREAD

**Issue by tedivm** [warrensbox/terraform-switcher#219]
**Is your feature request related to a problem? Please describe.**
I'm running a brand new laptop and installed it via brew.

**Describe the solution you'd like**
tfswitch installs and the commands all work, but the terraform command is never found.

**Describe alternatives you've considered**
The only alternative is to not use tfswitch.

**Additional context**
I'm using standard shell with standard options, so I'm not sure why it's failing out of the box.

## Required version
```sh
go version 1.13
```

**Comment by warrensbox** [comment]
For the time being, you have to use the `-b` option on the new M1 macs

### Use use the `-b` option or .tfswitch.toml file
This is similiar to using a .tfswitchrc file, but you can specify a custom binary path for your terraform installation

<img src="https://s3.us-east-2.amazonaws.com/kepler-images/warrensbox/tfswitch/tfswitch-v7.gif#1" alt="drawing" style="width: 370px;"/>

<img src="https://s3.us-east-2.amazonaws.com/kepler-images/warrensbox/tfswitch/tfswitch-v8.gif#1" alt="drawing" style="width: 370px;"/>

1. Create a custom binary path. Ex: `mkdir /Users/warrenveerasingam/bin` (replace warrenveerasingam with your username)
2. Add the path to your PATH. Ex: `export PATH=$PATH:/Users/warrenveerasingam/bin` (add this to your bash profile or zsh profile)
3. Pass -b or --bin parameter with your custom path to install terraform. Ex: `tfswitch -b /Users/warrenveerasingam/bin/terraform 0.10.8 `
4. Optionally, you can create a `.tfswitch.toml` file in your terraform directory(current directory) OR in your home directory(~/.tfswitch.toml). The toml file in the current directory has a higher precedence than toml file in the home directory
5. Your `.tfswitch.toml` file should look like this:
```ruby
bin = "/Users/warrenveerasingam/bin/terraform"
version = "0.11.3"
```
NOTE: (replace warrenveerasingam with your username)

**Comment by tpoindessous** [comment]
Hello,

I'm using tfswitch from a brew installation on mac m1 and it works without ~/.tfswitch.toml file.

**Comment by naveenkashyapdv** [comment]
If you are using zsh do the following.

Open .zshrc file nano $HOME/.zshrc

You will see the commented $PATH variable here

# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/...

Remove the comment symbol(#) and append your new path using a separator(:) like this.

export PATH=$HOME/bin:/usr/local/bin:/Users/ebin/Documents/Softwares/mongoDB/bin:$PATH

Activate the change source $HOME/.zshrc
You're done !!!

**Comment by schaabm** [comment]
If you using Ventura it could be that as standard zsh is active. Within the .zshrc file you have the block: 
`# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH`
activate the second line and source the file new ( `source $HOME/.zshrc` ) 
that worked for me.

**Comment by amrbisht** [comment]
If Nothing is working for you?
Then try these steps which I did:

- First I went to the Terraform download archive which can be found [here](https://releases.hashicorp.com/terraform/).
- Find your required version according to your mac.
- Download the zip file and unzip it, it will give you the terraform executable.
- Move the executable to the required location using the command
`sudo mv ./terraform /usr/local/bin`

You're done.
Check the version with 
`terraform --version`

**Comment by Jukie** [comment]
It also depends on version you're trying to use as shown at https://github.com/warrensbox/terraform-switcher/blob/master/lib/install.go#L99-L104
The arm64 binary only exists for >1.0.2

**Comment by apogrebnyak** [comment]
May be related to https://github.com/warrensbox/terraform-switcher/issues/303

Note, that if it cannot install to `/usr/local/bin/terraform` it falls back to installing to `~/bin/terraform`
Make sure that your `~/bin` directory is on your PATH.

To be fair, this message is emitted during terraform binary installation:
```
RUN `export PATH=$PATH:/Users/xxxxxx/bin` to append bin to $PATH
```
Here `xxxxxx` stands for your user account

**Comment by ericjohansson89** [comment]
One can also make use of a symbolic link
```
sudo ln -s ~/bin/terraform /usr/local/bin/terraform
```

**Comment by guhcampos** [comment]
The documentation should mention somewhere `tfswitch` expects the user `PATH` to contain `~/bin` - I didn't see it anywhere and this is not standard in most cases. The message mentioned in a previous comment suggesting an export is not there at all:

```
❯ tfswitch 
14:28:15.960 INFO Reading version from Terraform module at "."  
14:28:16.040 INFO Reading required version from constraint: ">= 1.9.0"  
14:28:16.041 INFO Matched version: "1.9.2"  
14:28:16.068 INFO Downloading to "/Users/gustavo/.terraform.versions/pgp-key.txt"  
14:28:16.510 INFO 7717 bytes downloaded  
14:28:16.511 INFO Downloading "https://releases.hashicorp.com/terraform/1.9.2/terraform_1.9.2_darwin_arm64.zip"  
14:28:16.511 INFO Downloading to "/Users/gustavo/.terraform.versions/terraform_1.9.2_darwin_arm64.zip"  
14:28:17.133 INFO 25720165 bytes downloaded  
14:28:17.133 INFO Downloading "https://releases.hashicorp.com/terraform/1.9.2/terraform_1.9.2_SHA256SUMS"  
14:28:17.133 INFO Downloading to "/Users/gustavo/.terraform.versions/terraform_1.9.2_SHA256SUMS"  
14:28:17.159 INFO 1378 bytes downloaded  
14:28:17.159 INFO Downloading "https://releases.hashicorp.com/terraform/1.9.2/terraform_1.9.2_SHA256SUMS.72D7468F.sig"  
14:28:17.159 INFO Downloading to "/Users/gustavo/.terraform.versions/terraform_1.9.2_SHA256SUMS.72D7468F.sig"  
14:28:17.189 INFO 566 bytes downloaded  
14:28:17.189 INFO Verifying signature of checksum file...  
14:28:17.191 INFO Checksum file signature verification successful.  
14:28:17.206 INFO Deleting "/Users/gustavo/.terraform.versions/terraform_1.9.2_SHA256SUMS"  
14:28:17.207 INFO Deleting "/Users/gustavo/.terraform.versions/terraform_1.9.2_SHA256SUMS.72D7468F.sig"  
14:28:17.587 INFO Switched Terraform to version "1.9.2"  
neverwonder/terraform on  main [!?] via 🐍 v3.12.4 (python-3.12) via 💠 default 
❯ terraform init
bash: terraform: command not found
```

**Comment by yermulnik** [comment]
I'm closing this one. Please shout out if you think it's worth of keeping it open for a reason.
