### ISSUE TITLE
using terraform_version_constraint in terragrunt.hcl doesn't seem to cause terraform version to change

### ISSUE THREAD

**Issue by MicNim** [warrensbox/terraform-switcher#220]
https://github.com/warrensbox/terraform-switcher/blob/092ccf5400887b7e02e296a8ff507fb2f6f7c4eb/main.go#L437

Working on implementing the "terraform_version_constraint" config for a stack that will uses multiple versions of terraform.

The current deployment consists of 3 modules 

module1 = terraform 0.14
module2 = terraform 0.14
module3 = terraform 0.13.6

Running 'terragrunt run-all init' elicits the following error:
`The currently installed version of Terraform (0.14.0) is not compatible with the version Terragrunt requires (>= 0.13, < 0.14).`

System versions:

terragrunt v0.36.3
tgswitch 0.5.389

terraform v0.14.0
tfswitch 0.13.1218

It's my expectation that when the "terraform_version_constraint" config is used then tfswitch will install the required version depending on the logical module being deployed?

Have I misunderstood the documentation/code, please help!

**Comment by warrensbox** [comment]
@ElDiabloRojo what happens when you run `tfswitch` in the same directory as the version.tf?
