### ISSUE TITLE
--chdir with absolute project paths not working

### ISSUE THREAD

**Issue by rolandjohann** [warrensbox/terraform-switcher#222]
Due to implementation we are not able to pass absolute paths to tfswitch:

https://github.com/warrensbox/terraform-switcher/blob/092ccf5400887b7e02e296a8ff507fb2f6f7c4eb/main.go#L74-L76

Before discovering `chdir` option we had to change dir at a sub shell, but were happy to discover a better way to reference terraform project directories and circumvent the problems involved by using subshells in bash scripts.

**Comment by Jukie** [comment]
Confirmed bug, PR incoming

**Comment by warrensbox** [comment]
@rolandjohann we have fixed this. This fix should be in the next release (tentatively May 27, 2022)

**Comment by rolandjohann** [comment]
@warrensbox thanks a lot!
