### ISSUE TITLE
`~> 1.0` should give me the same version as `>= 1.0.0, < 2.0.0` does

### ISSUE THREAD

**Issue by skyzyx** [warrensbox/terraform-switcher#226]
**Is your feature request related to a problem? Please describe.**

(_Branching off from [#224](https://github.com/warrensbox/terraform-switcher/issues/224#issuecomment-1122655220)…_)

I've been observing that using `~> 1.0` with `tfswitch` gives me the latest `1.0.x` release rather than the latest `1.x` release.

[Terraform's docs](https://www.terraform.io/language/expressions/version-constraints#-3) say:

> `~>`: Allows only the rightmost version component to increment. For example, to allow new patch releases within a specific minor release, use the full version number: `~> 1.0.4` will allow installation of `1.0.5` and `1.0.10` but not `1.1.0`. This is usually called the pessimistic constraint operator.

`~> 1.0` is expected to be equivalent to `>= 1.0.0, < 2.0.0`, but shorter.

I just upgraded a bunch of Homebrew packages yesterday, so now I have [0.13.1218](https://github.com/warrensbox/terraform-switcher/releases/tag/0.13.1218). But I've been observing it since Terraform 1.1 came out.

This is my alias for `cd`:

```bash
cdtfswitch() {
    builtin cd "$@" || true
    cdir=$PWD
    if [ -e "$cdir/versions.tf" ]; then
        tfswitch
    fi
}
```

`versions.tf` is:

```hcl
terraform {
  required_version = "~> 1.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.0"
    }
  }
}
```

**Describe the solution you'd like**

`~> 1.0` should give me the same version as `>= 1.0.0, < 2.0.0` does.

**Comment by llamahunter** [comment]
Isn't this actually https://github.com/warrensbox/terraform-switcher/issues/215, which was fixed in https://github.com/warrensbox/terraform-switcher/releases/tag/0.13.1218

**Comment by warrensbox** [comment]
@skyzyx 
The latest terraform version is `1.1.9`
Run show latest: `tfswitch -U`

In my version.tf, I have:
```sh
terraform {
  required_version = "~> 1.0"

  required_providers {
    aws        = ">= 2.52.0"
    kubernetes = ">= 1.11.1"
  }
}
```
When I run tfswitch in that directory, I get:
```
➜  test_versiontf git:(version_url_tweaks) ✗ tfswitch
Reading required version from terraform file
Reading required version from constraint: ~> 1.0
Matched version: 1.1.9
Switched terraform to version "1.1.9"

➜  test_versiontf git:(version_url_tweaks) ✗ terraform -v
Terraform v1.1.9
on darwin_amd64
```
Which is  `>= 1.0.0, < 2.0.0`

I am using tfswitch Version: 0.13.1221. Can you install the latest tfswitch and try again?

**Comment by skyzyx** [comment]
OK. It _has_ been an issue. Let me test this and try again.

**Comment by skyzyx** [comment]
Tested and working. Sorry for the late response. Resolving. Thank you!
