### ISSUE TITLE
Use new releases API

### ISSUE THREAD

**Issue by Jukie** [warrensbox/terraform-switcher#231]
#224 was an initial fix after the announcement of [the releases API](https://www.hashicorp.com/blog/announcing-the-hashicorp-releases-api) but the current implementation uses the old (but still supported) releases endpoint.

**Comment by rolandjohann** [comment]
It seems that the old endpoint doesn't work as expected:

```bash
tfswitch -l
Cannot get list from mirror: https://releases.hashicorp.com/terraform
```
