### ISSUE TITLE
Won't install on Raspberry pi: "warrensbox/terraform-switcher crit platform linux/armv7 is not supported."

### ISSUE THREAD

**Issue by JohnSmith31** [warrensbox/terraform-switcher#260]
Won't install on Raspberry pi: "warrensbox/terraform-switcher crit platform linux/armv7 is not supported."

**Comment by JohnSmith31** [comment]
Hi. I installed using the command on the tfswitch web page:

curl -L https://raw.githubusercontent.com/warrensbox/terraform-switcher/release/install.sh | bash

The full output is:

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9216  100  9216    0     0  19120      0 --:--:-- --:--:-- --:--:-- 19160
warrensbox/terraform-switcher crit platform linux/armv7 is not supported.  Make sure this script is up-to-date and file request at https://github.com/warrensbox/terraform-switcher/issues/new

**Comment by JohnSmith31** [comment]
(BTW, that's running on a Raspberry Pi 4 on Raspberry Pi OS. uname -a gives:
Linux mel 5.10.17-v7l+ #1403 SMP Mon Feb 22 11:33:35 GMT 2021 armv7l GNU/Linux)

**Comment by yermulnik** [comment]
@JohnSmith31 Would you mind trying `curl -L https://raw.githubusercontent.com/warrensbox/terraform-switcher/feature/add_more_platforms_to_install.sh/install.sh | bash` to see whether https://github.com/warrensbox/terraform-switcher/pull/261 fixes the issue for your platform? Thanks.

**Comment by yermulnik** [comment]
@JohnSmith31 ?

**Comment by JohnSmith31** [comment]
That certainly seemed to do the trick! Thanks :)

**Comment by yermulnik** [comment]
Cool. Thanks for confirmation.
Closing this issue to continue in #261
