### ISSUE TITLE
Use default branch for releases instead of release branch

### ISSUE THREAD

**Issue by nitrocode** [warrensbox/terraform-switcher#282]
**Is your feature request related to a problem? Please describe.**
Since the default branch is `master` (older commit) and the release branch is `release` (latest commit), a renovatebot configuration for atlantis keeps trying to change the dependency to an older commit. 

**Describe the solution you'd like**
- always merge to default branch and cut releases there instead of from the separate branch `release`
- or if the separate branch `release` is needed then make it default
- or please provide a renovatebot workaround confirm to track a specific golang dependency (tfswitch) releases from the `release` branch instead of the default branch

**Describe alternatives you've considered**
Nome

**Additional context**

- See PR https://github.com/runatlantis/atlantis/pull/2816
- Related pr from this repo https://github.com/warrensbox/terraform-switcher/pull/276

**Comment by nitrocode** [comment]
@warrensbox friendly ping. Please consider this change 🙏

**Comment by yermulnik** [comment]
Apparently this https://github.com/warrensbox/terraform-switcher/pull/351 is to switch from `release` to `master`.
