### ISSUE TITLE
-u -s arguments ignore .tfswitch.toml bin config

### ISSUE THREAD

**Issue by cdobbyn** [warrensbox/terraform-switcher#285]
**Is your feature request related to a problem? Please describe.**
When using either `-u` or `-s` arguments the value of "bin" in the `.tfswitch.toml` config is ignored.

**Describe the solution you'd like**
Unless presenting `-b` this should be placed in the location specified by `.tfswtich.toml`.

**Describe alternatives you've considered**
I used `-b` to get around my immediate issue.

**Additional context**

**Comment by Jukie** [comment]
Thanks for finding this! The problem is how the binPath is being fed into the functions. My PR should fix it.
