### ISSUE TITLE
Does tfswitch verifies the sha256sums?

### ISSUE THREAD

**Issue by vikas027** [warrensbox/terraform-switcher#290]
When `tfswitch` downloads a `terraform` binary, does it verifies the `sha256sum` advertised on hashicorp release site (https://releases.hashicorp.com/terraform)?
If yes, it will be good to advertise the same in the `README.md` :)

**Comment by apogrebnyak** [comment]
As far as I can tell it does not.

The download is done by this method -> https://github.com/warrensbox/terraform-switcher/blob/d7dfd1b44605b095937e94b981d24305b858ff8c/lib/download.go#L13

It is called from here and I don't see any signature verification until the method exits -> https://github.com/warrensbox/terraform-switcher/blob/master/lib/install.go#L136

I am not sure if `sha256` check will do anything to ensure clean source.  Only signature check against trusted key would.
It is not done here either.

**Comment by MatrixCrawler** [comment]
Duplicates #160
