### ISSUE TITLE
Add ability for .tfswitch.toml file to specify alternative terraform mirror URL.

### ISSUE THREAD

**Issue by apogrebnyak** [warrensbox/terraform-switcher#304]
Currently you can only specify `bin` and `version` parameters in .tfswitch.toml

Could you, please, add `mirror` parameter, so that alternative location, i.e. private binary repository can be specified?

Thanks.

**Comment by yermulnik** [comment]
Closing as duplicate of https://github.com/warrensbox/terraform-switcher/issues/274

**Comment by yermulnik** [comment]
@apogrebnyak Would you be up to work on this feature implementation?
