### ISSUE TITLE
New macOS security feature prevents terraform to run (installed via tfswitch)

### ISSUE THREAD

**Issue by ambis** [warrensbox/terraform-switcher#306]
macOS version: 13.3.1 (22E261)
Mac: MBP M1
tfswitch verision: 0.13.1308 (via brew)
commands:
```
$ tfswitch
# select version, test folder, and .tfswitch.toml says binary path is: ./
$ ./terraform init
```

and then this:

![MicrosoftTeams-image](https://user-images.githubusercontent.com/99065/235881698-d789528f-94c0-40d9-b515-06c41da789c3.png)

**Comment by yermulnik** [comment]
Is there anything `tfswitch` has to do with MacOS security? 🤔
I'm not a MacOS guy so I might miss context, though looking at the screenshot it seems to me that you shouldn't be installing Terraform with `tfswitch` into an arbitrary locations, but rather into "the Bin". For that you may need to adjust your `.tfswitch.toml` file. Please see the example at https://github.com/warrensbox/terraform-switcher#use-tfswitchtoml-file--for-non-admin---users-with-limited-privilege-on-their-computers

ps: if you do indeed need `terraform` binary to be installed at an arbitrary location, you'd probably need to exclude it from MacOS quarantine then: `xattr -d com.apple.quarantine /path/to/arbitrary/location/with/terraform/binary` (do it on your own risk).

**Comment by ambis** [comment]
Just to clairfy, "Move to Bin" in this context means "Move to Trash", not to "binaries folder".
