### ISSUE TITLE
Terraform command not found 

### ISSUE THREAD

**Issue by shivani-st** [warrensbox/terraform-switcher#316]
I installed terraform using ~ brew install warrensbox/tap/tfswitch 
However on running ~terraform version command, it gives error :  zsh: command not found: terraform

<img width="508" alt="image" src="https://github.com/warrensbox/terraform-switcher/assets/144203668/e84e5d76-cb40-4eb1-9e10-4bcb115c2065">

**Comment by yermulnik** [comment]
@shivani-st Ensure `/User/shivani_aher/bin` is on your `PATH` (refer to e.g. https://www.tutorialspoint.com/how-to-add-a-new-entry-to-the-path-variable-in-zsh-on-mac-os-in-linux; do it at your risk or seek assistance from a technician).

ps: please post text as text rather than as images.

**Comment by shivani-st** [comment]
Was resolved after being set to correct path. Thanks @yermulnik.
