### ISSUE TITLE
[Error] : Binary path does not exist: /usr/local/bin/terraform

### ISSUE THREAD

**Issue by ajax-mykhailo-oleksiuk** [warrensbox/terraform-switcher#319]
tfswitch & tgswitch don't install terraform/terragrunt at all and throw an error:

<img width="771" alt="Screenshot 2023-11-18 at 21 44 19" src="https://github.com/warrensbox/terraform-switcher/assets/110532903/f78248ab-2b25-474d-82cc-9ed0d113cdbd">

Steps to reproduce

1. Fresh Mac OS Sonoma 14.1.1 (23B81)
2. Install tfswitch/tgswitch using official docs: `brew install warrensbox/tap/tfswitch`
3. Run `tfswitch`

**Comment by yermulnik** [comment]
https://github.com/warrensbox/terraform-switcher?tab=readme-ov-file#use-tfswitchtoml-file--for-non-admin---users-with-limited-privilege-on-their-computers
