### ISSUE TITLE
Permissions Issues on linux

### ISSUE THREAD

**Issue by ajjl** [warrensbox/terraform-switcher#33]
After installing with `curl <script localtion> | sudo bash` I cannot actually do a `tfswitch`, I get the error:
```
2018/11/14 09:42:56 Creating directory for teraform: /home/aleinoff/.terraform.versions/
✔ 0.11.10
Downloading https://releases.hashicorp.com/terraform/0.11.10/terraform_0.11.10_linux_amd64.zip to terraform_0.11.10_linux_amd64.zip
Downloading ...
20940986 bytes downloaded.
lstat /usr/local/bin/terraform: no such file or directory
2018/11/14 09:43:04 Unable to create symlink. You must have SUDO privileges
```
running `sudo tfswitch` does work, but results in a terraform that is only available to the root user, which is undesirable.

Os version: ubuntu 18.something

Thanks!

**Comment by apr-1985** [comment]
Also seeing this on Mac High Sierra when installed via homebrew
`✔ 0.11.7
Downloading https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_darwin_amd64.zip to terraform_0.11.7_darwin_amd64.zip
Downloading ...
17754416 bytes downloaded.
2019/02/11 10:14:25 Unable to create symlink. You must have SUDO privileges`

**Comment by warrensbox** [comment]
I have updated the symlink error message to be more intuitive. The previous error message was misleading. Merge request #38 : 

```
log.Fatalf(`
	Unable to create new symlink.
	Maybe symlink already exist. Try removing existing symlink manually.
	Try running "unlink %s" to remove existing symlink.
	If error persist, you may not have the permission to create a symlink at %s.
	Error: %s`, dir, dir, err)
```

@ajjl requested a feature to allow users without admin privilege to install tfswitch. This feature is still not supported at the moment. However, please feel free to contribute and open a merge request to add this feature.

**Comment by bezerker** [comment]
I'd suggest having tfswitch just install the terraform binaries into the directory that you specify with -b.  I keep mine in /home/$USER/bin and put that in my path. Be great if this worked with that. This is kind of broken on linux otherwise

**Comment by evansj** [comment]
I'm also having issues on Mac because (due to company rules ☹️) my main user account isn't an admin account. It would be great if I could configure it to use `~/bin/terraform` instead of `/usr/local/bin/terraform`. Better still if it could read its config from something like `~/.tfswitch.conf` so I could set the directory in there instead of passing a command line argument every time.

**Comment by MichaelSmyth0184** [comment]
I just gave my current user owner on the /usr/local/bin folder and worked like magic.

`sudo chown -R $USER /usr/local/bin`

Might not be great from a security perspective, but works none the less.

**Comment by evansj** [comment]
@MichaelSmyth0184 that would work great. Unfortunately I can't do that, due to the aforementioned company rules...

**Comment by MichaelSmyth0184** [comment]
@evansj Yeah I guess having sudo permissions is a luxery at some companies...

Have you tried downloading from source and modifying destination folder to something you have ownership over? Shouldn't be too difficult I would imagine.

**Comment by evansj** [comment]
@MichaelSmyth0184 I intend to do that, and hopefully create a PR

**Comment by warrensbox** [comment]
@evansj @ajjl 
I released a pre-released version with the option to install `tfswitch` to a user specifed directory.

You can download the pre-release version here (based on your OS): https://github.com/warrensbox/terraform-switcher/releases/tag/0.7.0
1.  Create bin path directory. Ex: `mkdir /Users/warrenveerasingam/bin`
2. Add custom bin path to PATH env: `export PATH=$PATH:/Users/warrenveerasingam/bin`
3. Test pre-release version `./tfswitch -b /Users/warrenveerasingam/bin/terraform`. Install any version.
4.  Validate terraform version. `terraform -v`


Otherwise, you can `git pull` and compile from the source.
1. To compile from the source, you must checkout the `feature/unprivilege-user` branch (https://github.com/warrensbox/terraform-switcher/tree/feature/unprivilege-user)
2. `dep ensure` or `go get -v -t -d ./...`
3. `go build -v -o tfswitch`
4.  Create bin path directory. Ex: `mkdir /Users/warrenveerasingam/bin`
5. Add custom bin path to PATH env: `export PATH=$PATH:/Users/warrenveerasingam/bin`
6. Test pre-release version `./tfswitch -b /Users/warrenveerasingam/bin/terraform`. Install any version.
7.  Validate terraform version. `terraform -v`


I will merge `feature/unprivilege-user` branch to the `master` branch and release it once we can verify it's working as expected.

I will release an option with the `~/.tfswitch.conf` soon but not for this release.

Please feel free to contribute and comment. Thanks for helping me test it out.

**Comment by evansj** [comment]
@warrensbox I've been using the pre-release version today and it works perfectly - thanks!

**Comment by warrensbox** [comment]
Released : 0.7.737
https://github.com/warrensbox/terraform-switcher/releases/tag/0.7.737
Features: 
Option to use -b parameter to specify custom terraform installtion location:
`tfswitch -b /Users/warrenveerasingam/bin/terraform 0.10.8`
Option to use `.tfswitch.toml` file. For example:
```
bin = "/Users/warrenveerasingam/bin/terraform"
version = "0.11.3"
```
After that, you can simply run `tfswitch` and it should automatically update your terraform version according to the configuration provided. 

<img src="https://s3.us-east-2.amazonaws.com/kepler-images/warrensbox/tfswitch/tfswitch-v7.gif" alt="drawing" style="width: 270px;"/>
<img src="https://s3.us-east-2.amazonaws.com/kepler-images/warrensbox/tfswitch/tfswitch-v8.gif" alt="drawing" style="width: 270px;"/>
You can also automate the switching by adding the following to your profile:

Automatically switch with bash

Add the following to the end of your ~/.bashrc file: (Use either .tfswitchrc or .tfswitch.toml)
```
cdtfswitch(){
  builtin cd "$@";
  cdir=$PWD;
  if [ -f "$cdir/.tfswitchrc" ]; then
    tfswitch
  fi
}
alias cd='cdtfswitch'
```
Automatically switch with zsh

Add the following to the end of your ~/.zshrc file:
```
load-tfswitch() {
  local tfswitchrc_path=".tfswitch.toml"

  if [ -f "$tfswitchrc_path" ]; then
    tfswitch
  fi
}

add-zsh-hook chpwd load-tfswitch
load-tfswitch
```
> NOTE: if you see an error like this: command not found: add-zsh-hook, then you might be on an older version of zsh (see below), or you simply need to load add-zsh-hook by adding this to your .zshrc:

> autoload -U add-zsh-hook

older version of zsh
```
cd(){
  builtin cd "$@";
  cdir=$PWD;
  if [ -f "$cdir/.tfswitch.toml" ]; then
    tfswitch
  fi
}
```

To get the latest version of `tfswitch`:
With Brew:
```
brew upgrade warrensbox/tap/tfswitch
```
Other upgrades:
```
curl -L https://raw.githubusercontent.com/warrensbox/terraform-switcher/release/install.sh | bash
```
Please open or comment on this issue if you see any bug!

**Comment by weyderfs** [comment]
Guys I fixed here adding sudo after |
`url -L https://raw.githubusercontent.com/warrensbox/terraform-switcher/release/install.sh | sudo bash`
But to use _tfswitch_ and Terraform I needed continuous using SUDO
`sudo tfswtich`
`sudo terraform`

But works here

Ubuntu 18.04.3 LTS \n \l

**Comment by mickmorseMB** [comment]
Just create an alias in your bashrc called tfs

alias tfs="tfswitch -b /home/user/bin"

that way your custom directory alwats persists.

**Comment by alok15ee** [comment]
> @evansj @ajjl
> I released a pre-released version with the option to install `tfswitch` to a user specifed directory.
> 
> You can download the pre-release version here (based on your OS): https://github.com/warrensbox/terraform-switcher/releases/tag/0.7.0
> 
> 1. Create bin path directory. Ex: `mkdir /Users/warrenveerasingam/bin`
> 2. Add custom bin path to PATH env: `export PATH=$PATH:/Users/warrenveerasingam/bin`
> 3. Test pre-release version `./tfswitch -b /Users/warrenveerasingam/bin/terraform`. Install any version.
> 4. Validate terraform version. `terraform -v`
> 
> Otherwise, you can `git pull` and compile from the source.
> 
> 1. To compile from the source, you must checkout the `feature/unprivilege-user` branch (https://github.com/warrensbox/terraform-switcher/tree/feature/unprivilege-user)
> 2. `dep ensure` or `go get -v -t -d ./...`
> 3. `go build -v -o tfswitch`
> 4. Create bin path directory. Ex: `mkdir /Users/warrenveerasingam/bin`
> 5. Add custom bin path to PATH env: `export PATH=$PATH:/Users/warrenveerasingam/bin`
> 6. Test pre-release version `./tfswitch -b /Users/warrenveerasingam/bin/terraform`. Install any version.
> 7. Validate terraform version. `terraform -v`
> 
> I will merge `feature/unprivilege-user` branch to the `master` branch and release it once we can verify it's working as expected.
> 
> I will release an option with the `~/.tfswitch.conf` soon but not for this release.
> 
> Please feel free to contribute and comment. Thanks for helping me test it out.

Thanks, This works for mac!!

**Comment by andremacdowell** [comment]
> I just gave my current user owner on the /usr/local/bin folder and worked like magic.
> 
> `sudo chown -R $USER /usr/local/bin`
> 
> Might not be great from a security perspective, but works none the less.

This actually works well if you just want the solution for local wsl2 usage.

**Comment by troy-mac** [comment]
@warrensbox any chance you will be fixing this on WSL Ubuntu?  I have tried everything above, even chown of /usr/local/bin and nothing works. Not sure why there is a need to put everything in /usr/local/bin why can't a user just install to their home directory.

**Comment by troy-mac** [comment]
Seems I got it to work with using snap install.  BUT all that said when I open another terminal I get the same issue I have to sudo to use it.  FYI snap on WSL would not work until I ran these commands.  
`sudo apt-get update && sudo apt-get install -yqq daemonize dbus-user-session fontconfig
sudo daemonize /usr/bin/unshare --fork --pid --mount-proc /lib/systemd/systemd --system-unit=basic.target
exec sudo nsenter -t $(pidof systemd) -a su - $LOGNAME`

[(https://github.com/microsoft/WSL/issues/5126 )]

**Comment by sbuckpesch** [comment]
For me the `.tfswitch.toml` solution works perfectly on WSL2 without changing any permissions on /usr/local/bin

```bash
# Go to user home
cd 

# Install tfswitch
curl -L https://raw.githubusercontent.com/warrensbox/terraform-switcher/release/install.sh | sudo bash
mkdir bin
export BIN_PATH=$(echo $PWD)/bin

# Create .tfswitch.toml
cat >> .tfswitch.toml << EOF
bin = "${BIN_PATH}/terraform"
EOF

# Install your first terraform version
tfswitch

# Put your new binary path to .zshrc or .bashrc
cat >> .zshrc << EOF
export PATH=${BIN_PATH}:\$PATH
EOF

# Restart your console. Done 🎉
terraform --version
```

**Comment by lauchlan105** [comment]
For anyone coming to this thread in 2022...

#### This script;
- Works on WSL2 ✔️ 
- doesn't require `sudo` ✔️
- installs it only for the current user

Note: I chose `~/bin` for `TFSWITCH_DIR` as that is also where `tfswitch` installs  the terraform binaries. And, I've confirmed that changing terraform versions will not result in the `tfswitch` binary being removed.

```bash
# Location of where you'd like to save the binary
# This is not important to tfswitch, only important to this here script
TFSWITCH_DIR=~/bin

# go to home dir
cd ~

# download the install script
curl -L https://raw.githubusercontent.com/warrensbox/terraform-switcher/release/install.sh >> install.sh

# ensure the directory for the `tfswitch` bin exists
mkdir -p $TFSWITCH_DIR

# run install script (with -b to indicate desired path to save binary)
sh install.sh -b $TFSWITCH_DIR

# remove the install script as it is no longer needed
rm install.sh

# add the TFSWITCH_DIR to your path so the binaries can be executed from anywhere
# NOTE: this may be ~/.bashrc, or ~/.zshrc, or others, but if you don't know, safest not to change it 
echo 'export PATH="$PATH:'$TFSWITCH_DIR'"' >> ~/.bash_profile
```

If you cannot use `tfswitch` after restarting your terminal session...
1. check the `tfswitch` binary exists at the path you specified for `$TFSWITCH_DIR`
    a. if it does exist, the last step is where things went wrong - it likely added the `export` to a 
       file that is not included in your bash profile - The "Where to put it" section in [this](https://unix.stackexchange.com/questions/26047/how-to-correctly-add-a-path-to-path) may help you.
2. if you ran into issues at the installation step, try replacing `sh` with `bash`

**Comment by LordOfTheJinx** [comment]
i switched to root and ran the script, It worked. May not apply to everyone but one could give this a try. Using sudo to install didn't help. Can use 'tfswitch' as a regular user.

`Someguy@Playbook:~/Projects/Crest/terraform$ sudo 'curl -L https://raw.githubusercontent.com/warrensbox/terraform-switcher/release/install.sh | bash'
sudo: curl -L https://raw.githubusercontent.com/warrensbox/terraform-switcher/release/install.sh | bash: command not found
Someguy@Playbook:~/Projects/Crest/terraform$ sudo curl -L https://raw.githubusercontent.com/warrensbox/terraform-switcher/release/install.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9272  100  9272    0     0  23295      0 --:--:-- --:--:-- --:--:-- 23355
warrensbox/terraform-switcher info checking GitHub for latest tag
warrensbox/terraform-switcher info found version: 0.13.1308 for 0.13.1308/linux/amd64
install: cannot create regular file '/usr/local/bin/tfswitch': Permission denied
Someguy@Playbook:~/Projects/Crest/terraform$ sudo -i
root@Playbook:~# curl -L https://raw.githubusercontent.com/warrensbox/terraform-switcher/release/install.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9272  100  9272    0     0  92153      0 --:--:-- --:--:-- --:--:-- 92720
warrensbox/terraform-switcher info checking GitHub for latest tag
warrensbox/terraform-switcher info found version: 0.13.1308 for 0.13.1308/linux/amd64
warrensbox/terraform-switcher info installed /usr/local/bin/tfswitch
Someguy@Playbook:~# 
Someguy@Playbook:~# exit
logout
Someguy@Playbook:~/Projects/Crest/terraform$ 
Someguy@Playbook:~/Projects/Crest/terraform$ tfswitch 
Creating directory for terraform binary at: /home/Someguy/.terraform.versions
✔ 1.5.2
Unable to write to: /usr/local/bin/terraform
Creating bin directory at: /home/Someguy/bin
Creating directory for terraform binary at: /home/Someguy/bin
RUN `export PATH=$PATH:/home/Someguy/bin` to append bin to $PATH
Downloading to: /home/Someguy/.terraform.versions
20957185 bytes downloaded
Switched terraform to version "1.5.2" 
Someguy@Playbook:~/Projects/Crest/terraform$ `

**Comment by Dvelezs94** [comment]
So by default tfswitch tries to place the terraform binary under `/usr/local/bin`, which normal users don't have access to write to.

For this, @warrensbox added a flag to install terraform on a specified directory

```shell
tfswitch -b ${HOME}/.local/bin/terraform
```

however, writing this command every time you want to switch terraform versions is a pain, so you can easily just add it to your .bashrc (or similar)

```shell
alias tfswitch="tfswitch -b ${HOME}/.local/bin/terraform"
```

**Comment by yermulnik** [comment]
> however, writing this command every time you want to switch terraform versions is a pain, so you can easily just add it to your .bashrc (or similar)

There's a bit easier programmatical approach: https://tfswitch.warrensbox.com/usage/config-files/#use-tfswitchtoml-file-for-non-admin-users-with-limited-privilege-on-their-computers
![image](https://github.com/user-attachments/assets/e26c7a17-db6d-48ff-bd49-834427b10dfa)

_👉🏻 Apologies for screenshot of the text — couldn't preserve formatting when copy-pasting as text 🤷🏻_
