### ISSUE TITLE
BUG: Terraform not switching

### ISSUE THREAD

**Issue by GodAtum360** [warrensbox/terraform-switcher#330]
When I run:

` tfswitch -l
Creating directory for terraform binary at: /home/christopher/.terraform.versions
✔ 1.6.6
Unable to write to: /usr/local/bin/terraform
Creating bin directory at: /home/christopher/bin
Creating directory for terraform binary at: /home/christopher/bin
RUN `export PATH=$PATH:/home/christopher/bin` to append bin to $PATH
Downloading to: /home/christopher/.terraform.versions
24976120 bytes downloaded
Switched terraform to version "1.6.6" `

TF still stays at 1.7.5. It should switch to 1.6.6

```
 terraform -v
Terraform v1.7.5
on linux_amd64
```

**Comment by yermulnik** [comment]
@GodAtum360 Would you please share the output of `which terraform` command?
If you have `terraform` binary installed by any other mean than `tfswitch`, please de-install it before using `tfswitch`. Alternatively you may want to move `$HOME/bin` **before** any other `bin` dirs on your `PATH` env var, e.g.: `export PATH="$HOME/bin:$PATH"` and then additionally add it to your `~/.bashrc` to make this permanent.
