### ISSUE TITLE
Fallback to ~/bin if /usr/local/bin doesn't exist

### ISSUE THREAD

**Issue by alkesander** [warrensbox/terraform-switcher#331]
Please add an additional check if folder /usr/local/bin exists and if not - fall back to ~/bin folder, as expected. I'm using nixOS and /usr/local/bin doesn't exist there. The output is:

```
[Error] : Binary path does not exist: /usr/local/bin/terraform
[Error] : Manually create bin directory at: /usr/local/bin and try again.
```

Instead after creating this folder as root (I don't want to use this folder): 

```
Unable to write to: /usr/local/bin/terraform
Creating bin directory at: /home/usr/bin
Creating directory for terraform binary at: /home/usr/bin
RUN `export PATH=$PATH:/home/usr/bin` to append bin to $PATH
```

That would be much appreciated.

**Comment by yermulnik** [comment]
https://github.com/warrensbox/terraform-switcher?tab=readme-ov-file#use-tfswitchtoml-file--for-non-admin---users-with-limited-privilege-on-their-computers
```shell
> cat ~/.tfswitch.toml
bin = "$HOME/bin/terraform"
```
