### ISSUE TITLE
Latest release 1.0.0 does not support glibc 2.31 or lower

### ISSUE THREAD

**Issue by PabloRapidScale** [warrensbox/terraform-switcher#344]
**Is your feature request related to a problem? Please describe.**
The latest 1.0.0 release has a dependency on glibc 2.32 or higher which is not available on Ubuntu 20.04 LTS natively. This is not called out in the release notes, so anyone with an older OS may experience issues that were not present in the previous version of tfswitch.

**Describe the solution you'd like**
Ideally backwards compatibility would be nice, but if that's not feasible it should at least be called out in the release notes for the uninformed. 

**Describe alternatives you've considered**
I used the tag feature to lock the version to 0.13.1308 which still works. 
```sh
curl -L https://raw.githubusercontent.com/warrensbox/terraform-switcher/release/install.sh |  bash -s -- -b  $HOME/.local/bin 0.13.1308
```
Or for those using the CI steps from documentation like me:
```sh
wget https://raw.githubusercontent.com/warrensbox/terraform-switcher/release/install.sh  #Get the installer on to your machine:

chmod 755 install.sh #Make installer executable

./install.sh -b $HOME/.bin -d 0.13.1308 #Install tfswitch in a location you have permission and lock the version to 0.13.1308 for those without a newer version of glibc:

$HOME/.bin/tfswitch #test

export PATH=$PATH:$HOME/.bin #Export your .bin into your path

#You should probably add step 4 in your `.bash_profile` in your $HOME directory.

#Next, try:
`tfswitch -b $HOME/.bin/terraform 0.11.7` 

#or simply 

`tfswitch -b $HOME/.bin/terraform`
```
**Additional context**
```sh
$ lsb_release -a
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal

$ ldd --version | head -n1
ldd (Ubuntu GLIBC 2.31-0ubuntu9.14) 2.31

# Error
$ tfswitch
tfswitch: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by tfswitch)
tfswitch: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by tfswitch)
```

**Comment by yermulnik** [comment]
FYI: https://github.com/warrensbox/terraform-switcher/pull/346

Btw re the `-b` flag — you can use `~/.tfswitch.toml` to "automate" that:
```shell
> cat ~/.tfswitch.toml
bin = "$HOME/bin/terraform"
```

**Comment by yermulnik** [comment]
New version will be available in a bit.
