### ISSUE TITLE
GLIBC 2.31 - No Longer Supported ?

### ISSUE THREAD

**Issue by melbit-michaelw** [warrensbox/terraform-switcher#345]
**Is your feature request related to a problem? Please describe.**
Version 0.13.1300 worked with glibc 2.31.

Version 1.0.0+ now require glibc 2.32 or 2.34. 

Was this an intentional change ? 

We use tfswitch primarily on an older (but still supported albeit only for another couple of months) Debian Bullseye container. As a result of this change, we can no longer use the latest version of tfswitch.  

We are planning to upgrade our build container regardless, but wanted to ensure that this was a deliberate change rather than accidental.

**Comment by yermulnik** [comment]
FYI: https://github.com/warrensbox/terraform-switcher/pull/346

**Comment by yermulnik** [comment]
New version will be available in a bit.
