### ISSUE TITLE
Why is the test for linux including build tasks?

### ISSUE THREAD

**Issue by MatrixCrawler** [warrensbox/terraform-switcher#372]
I was looking at the integration tests and i don't understand wha the code for the linux tests is at it is

https://github.com/warrensbox/terraform-switcher/blob/fe07d8bd0d6f22cfa3fab4f8aa69742411509906/.github/workflows/build.yml#L35-L45

I looks like it is 
- get dependecies (what should be done with actions/setup-go already
- go vet (which might be useful for windows tests too)
- go test (necessary of course)
- create build dir (why?)
- build tfswitch  (again why? these are integration tests)
- create /bin dir (why?)
- iterate the test-data folders and execute the built binary with them as changedir params. (i can see that this MIGHT be useful, but this should be covered in the test definitions. Did that in #356)

Maybe there is something i don't get. If that is the case: please enlighten me 😁 

If that is a good approach: Why not doing it with windows test as well?

**Comment by warrensbox** [comment]
@MatrixCrawler this was implemented awhile back. I think @jukie helped with this tests. It was more of an integration test. 
I am open to switching it to unit tests - like what you were doing with #356 

Thanks for optimizing the test as well.

**Comment by MatrixCrawler** [comment]
Tanks for the info 😄
