### ISSUE TITLE
We are facing the issue with the latest version(v1.1.0) of tfswitcher

### ISSUE THREAD

**Issue by mrityunjaybiswas** [warrensbox/terraform-switcher#402]
Our pipeline was running fine with v1.0.2, but suddenly in one step our pipeline download the latest tfswitcher(v1.1.0) and then pipeline got failed. We are facing the below error :

FATAL Error parsing configuration file: "exact constraint (\"= 1.1.9, = 1.1.9\") cannot be combined with other conditions"

**Comment by MatrixCrawler** [comment]
Likely the same issue as in #400 
We are working on a fix for that

**Comment by yermulnik** [comment]
@mrityunjaybiswas Can you please share the `required_version` from your TF configuration files (from all of them)?
