### ISSUE TITLE
install.sh does not support non v-prefixed tags

### ISSUE THREAD

**Issue by 7opf** [warrensbox/terraform-switcher#413]
Looks like you moved to v-prefixed tags and install.sh assumes this v-prefix to be present. This probably doesn't break the default "latest" usecase, but breaks the specific tag use case for tags pre v-prefix.

**Comment by warrensbox** [comment]
We can a fix for that: https://github.com/warrensbox/terraform-switcher/pull/405

It will be released shortly.

**Comment by MatrixCrawler** [comment]
Please wait for Release 1.1.1. This issue is already fixed with #405
