### ISSUE TITLE
Install script issue

### ISSUE THREAD

**Issue by shelardipak** [warrensbox/terraform-switcher#431]
Called install.sh script using following command by passing version tag but it fails to execute entire script. fails somewhere in execute function. Unable to figure it out exact which line it is failing (Version i am passing is 1.0.2)

`curl -L https://raw.githubusercontent.com/warrensbox/terraform-switcher/release/install.sh | bash -s -- $VERSION`

![image](https://github.com/warrensbox/terraform-switcher/assets/61777346/eedbc965-d817-4dee-96eb-5be33322b4e3)

Apparently it is failing somewhere in execute function but there is no way to debug it.

**Comment by yermulnik** [comment]
Oh, the links in the README and docu site are from the past when we used another branch for releases 🤦🏻 
Please use https://raw.githubusercontent.com/warrensbox/terraform-switcher/master/install.sh instead

**Comment by shelardipak** [comment]
Thanks you very much.. After using updated URL my code is working fine now :)
