### ISSUE TITLE
OpenTofu binary installed as terraform.exe instead of tofu.exe on Windows

### ISSUE THREAD

**Issue by mj790** [warrensbox/terraform-switcher#482]
Not sure if this is done on purpose or not but OpenTofu binary on Windows is installed as terraform.exe instead of tofu.exe. Last 3 lines of debug output showing the download works properly but the symlink part installs it with the wrong name. 

```
DEBUG [files.go:19,RenameFile] Renaming file "C:\\Users\\mj790\\.terraform.versions\\tofu.exe" to "C:\\Users\\mj790\\.terraform.versions\\opentofu_1.7.1.exe"
DEBUG [symlink.go:118,ChangeProductSymlink] Symlink created at "C:\\Users\\mj790/bin/terraform.exe"
INFO [install.go:116,switchToVersion] Switched OpenTofu to version "1.7.1"
```

**Comment by warrensbox** [comment]
Do you have a custom user bin path?
Are you using a toml file to specify your bin directory?

**Comment by MatthewJohn** [comment]
I'm assuming it's related to: https://github.com/warrensbox/terraform-switcher/blob/master/lib/defaults.go#L8, which is used by https://github.com/warrensbox/terraform-switcher/blob/4f00243e7a5423684ffa5c1a42fc57a0ffb952bf/lib/param_parsing/parameters.go#L153

**Comment by mj790** [comment]
> Do you have a custom user bin path? Are you using a toml file to specify your bin directory?

Looks like the issue has been found and resolved but just for reference I had no custom path and no toml file.
