### ISSUE TITLE
Bug: Misleading error message when directories for binaries don't exist.

### ISSUE THREAD

**Issue by tymik** [warrensbox/terraform-switcher#493]
**Is your feature request related to a problem? Please describe.**
When installing first terraform with tfswitch I was given the following error:

```
FATAL Unable to find existing directory in "/usr/local/bin/terraform or /Users/${CURRENT_USER}/bin/terraform". Manually create one of them and try again.
```

So I created `/Users/${CURRENT_USER}/bin/terraform` and I got another error:

```
FATAL 
		Unable to create new symlink.
		Maybe symlink already exist. Try removing existing symlink manually.
		Try running "unlink "/Users/${CURRENT_USER}/bin/terraform"" to remove existing symlink.
		If error persist, you may not have the permission to create a symlink at "/Users/${CURRENT_USER}/bin/terraform".
		Error: symlink /Users/${CURRENT_USER}/.terraform.versions/terraform_1.2.4 /Users/${CURRENT_USER}/bin/terraform: file exists
```

I thought in the first place that `/Users/${CURRENT_USER}/bin/terraform` should be the final binary symlink, not the directory, but I assumed that it may be different and the message is right - seems that it is not.
This is misleading error message.

**Describe the solution you'd like**

The message should say instead:

```
FATAL Unable to find existing directory in "/usr/local/bin or /Users/${CURRENT_USER}/bin". Manually create one of them and try again.
```

as the `terraform` is for the binary and cannot be a directory.

**Describe alternatives you've considered**
I consider no alternatives for this issue.

**Additional context**
Initial setup of tfswitch, rather a minor issue that probably everyone eventually resolves.

**Comment by yermulnik** [comment]
Thanks for raising this. I attempted to streamline this via https://github.com/warrensbox/terraform-switcher/pull/494
