### ISSUE TITLE
Signature check causing tfswitch to fail on air-gapped environments

### ISSUE THREAD

**Issue by alejandro-ripoll** [warrensbox/terraform-switcher#496]
tfswitch version: v1.2.2

**Description**
When running tfswitch on an air-gapped environment and providing a mirror for terraform releases, it will still try to connect to https://www.hashicorp.com/.well-known/pgp-key.txt and installation will fail in case it's unreachable.

I haven't found any way to override this behaviour via:
- Providing an alternative mirror for https://www.hashicorp.com/.well-known/pgp-key.txt.
- Provide pgp-key via an existing file.
- Disable signature check.

Thanks

**Steps to reproduce**
Execute tfswitch on an server with no network access to https://www.hashicorp.com/
```
$ tfswitch -g DEBUG  --mirror="https://REDACTED-MY-INTERNAL-MIRROR" 1.9.3
08:05:47.528 DEBUG [versiontf.go:73,isTerraformModule] No required version constraints defined by Terraform module at "/tmp"
08:05:47.528 DEBUG [install.go:222,InstallProductVersion] Install version 1.9.3. Dry run: false
08:05:47.528 DEBUG [list_versions.go:41,getTFList] Getting list of versions
08:05:47.576 DEBUG [download.go:134,downloadPublicKey] Looking up public key file at "/home/USER/.terraform.versions/terraform_72D7468F.asc"
08:05:47.576 INFO [download.go:99,downloadFromURL] Downloading to "/home/USER/.terraform.versions/pgp-key.txt"
08:05:47.907 ERROR [download.go:103,downloadFromURL] Error downloading https://www.hashicorp.com/.well-known/pgp-key.txt: Get "https://www.hashicorp.com/.well-known/pgp-key.txt": read tcp REDACTED:42556->76.76.21.9:443: read: connection reset by peer
08:05:47.907 ERROR [download.go:140,downloadPublicKey] Error fetching public key file from https://www.hashicorp.com/.well-known/pgp-key.txt
08:05:47.907 ERROR [download.go:27,DownloadProductFromURL] Could not download public PGP key file.
08:05:47.907 FATAL [install.go:89,install] Error downloading: Get "https://www.hashicorp.com/.well-known/pgp-key.txt": read tcp REDACTED:42556->76.76.21.9:443: read: connection reset by peer
```

**Comment by yermulnik** [comment]
Sounds similar to cURL's `--insecure (-k)` option to me: do not verify PGP/GPG signature when explicitly requested on command line (or via env var?).
Or is this request more of about an option to download signature from the local mirror?

Cc @warrensbox @MatthewJohn

**Comment by MatthewJohn** [comment]
> Provide pgp-key via an existing file.

This should certainly be do-able, it should only download the GPG key if it doesn't exist. However, it does store it (for terraform) in:
```
$HOME/.terraform.versions/terraform_72D7468F.asc
```

Unless you meant as a command line argument?

**Comment by alejandro-ripoll** [comment]
> > Provide pgp-key via an existing file.
> 
> This should certainly be do-able, it should only download the GPG key if it doesn't exist. However, it does store it (for terraform) in:
> 
> ```
> $HOME/.terraform.versions/terraform_72D7468F.asc
> ```
> 
> Unless you meant as a command line argument?

That totally works for me and sounds much better than signature check.

Thanks @MatthewJohn.
