### ISSUE TITLE
.terraform-version is ignored and latest version is installed

### ISSUE THREAD

**Issue by jda258** [warrensbox/terraform-switcher#500]
We have been using tfswitch for years now without issue. We updated our image to include the latest tfswitch version 1.2.2, and it is ignoring the version we've specified in .terraform-version.

```
❯ cat .terraform-version
1.4.6
```
```
❯ tfswitch
18:10:16.369 INFO Reading configuration from "/Users/josh/workspace/eks-cluster/cluster-bootstrap/.terraform-version"
18:10:16.570 INFO Reading version from Terraform module at "."
18:10:16.768 INFO Reading required version from constraint: ">= 1.3.6"
18:10:16.771 INFO Matched version: "1.9.5"
18:10:16.790 INFO Downloading to "/Users/josh/.terraform.versions/pgp-key.txt"
18:10:17.167 INFO 7717 bytes downloaded
18:10:17.167 INFO Downloading "https://releases.hashicorp.com/terraform/1.9.5/terraform_1.9.5_darwin_arm64.zip"
18:10:17.167 INFO Downloading to "/Users/josh/.terraform.versions/terraform_1.9.5_darwin_arm64.zip"
18:10:18.405 INFO 25737301 bytes downloaded
18:10:18.406 INFO Downloading "https://releases.hashicorp.com/terraform/1.9.5/terraform_1.9.5_SHA256SUMS"
18:10:18.406 INFO Downloading to "/Users/josh/.terraform.versions/terraform_1.9.5_SHA256SUMS"
18:10:18.419 INFO 1378 bytes downloaded
18:10:18.419 INFO Downloading "https://releases.hashicorp.com/terraform/1.9.5/terraform_1.9.5_SHA256SUMS.72D7468F.sig"
18:10:18.419 INFO Downloading to "/Users/josh/.terraform.versions/terraform_1.9.5_SHA256SUMS.72D7468F.sig"
18:10:18.433 INFO 566 bytes downloaded
18:10:18.455 INFO Verifying signature of checksum file...
18:10:18.461 INFO Checksum file signature verification successful.
18:10:18.489 INFO Deleting "/Users/josh/.terraform.versions/terraform_1.9.5_SHA256SUMS"
18:10:18.490 INFO Deleting "/Users/josh/.terraform.versions/terraform_1.9.5_SHA256SUMS.72D7468F.sig"
18:10:18.928 INFO Switched Terraform to version "1.9.5"
```

**Comment by yermulnik** [comment]
Recently we had gone through huge re-factoring and revamping. Current order of precedence is outlined at https://tfswitch.warrensbox.com/usage/general/ (TF `required_version` takes precedence over `.terraform-version`).
Would it be feasible for you to switch to using `TF_VERSION` env var, which has highest precedence?

Also, out of interest, what's the use case and background of setting this permissive TF version constraint via `required_version` and then override it via external means?

**Comment by yermulnik** [comment]
> Thanks @yermulnik ! We didn't realize the order of precedence had changed. It might be good to include that as a breaking change on the latest release notes.

It didn't come with the latest version. When we switched from v0 to v1 we did some refactoring, though — among other things — we made a mistake in a precedence order, hence after that we revamped it an implemented it as much close to what existed in v0 as possible. But, you're right, we indeed missed to announce that explicitly, mostly because the difference was minimal as we saw it. Apologies for that and for the frustration it brought into your flow.

> The directory we run tfswitch from had multiple environments in subdirectories with different versions.tf files. We were able to combine them into one in the root directory, so all is good now.

Glad to hear you've resolved it.

Are you ok with closing this issue then?

**Comment by jda258** [comment]
No worries, and thanks for your work on this great project!
