### ISSUE TITLE
Consider .tofu files

### ISSUE THREAD

**Issue by braun1928** [warrensbox/terraform-switcher#508]
Starting with opentofu 1.8.0, it can read `<file>.tofu` as well as .tf files, preferring the former if the file names are the same. tfswitch should follow that when issuing `-t opentofu` to consider the `.tofu` files to define the version.

**Comment by yermulnik** [comment]
`tfswitch` doesn't rely on file extension directly, but instead relies upon `tfconfig` library: https://github.com/hashicorp/terraform-config-inspect

While your feature request makes sense to me, do you by any chance know does OpenTofu provide the counterpart for `tfconfig` lib?

ps: obviously it would be great for the underlying library to add support for OpenTofu-specific file extension, though I'm a bit hesitant on whether Hashicorp would be really keen to implement that any time soon I guess 🤷🏻

**Comment by braun1928** [comment]
I didn't see any fork of that repo; I found a commit in 1.8.0 tree "OpenTofu Specific Code Override: Add support to .tofu files" that does [exactly](https://github.com/opentofu/opentofu/commit/ab289fc07c4dbbb75eecb2b526e8e8abbf23c5fd#diff-25ade80935f9d3d9172f35b7e6ce6ccfeb5286ea6e2e8f468c73fe9192e034a3R246) what I described.

I doubt Hashi will do that change on their repo, though, and I haven't seen if that repo being forked to add this change (or similar) is on opentofu's roadmap as well.

**Comment by yermulnik** [comment]
> to add this change (or similar) is on opentofu's roadmap as well.

Well, given OpenTofu has started to diverge from Terraform, I guess we should then hope for them to start providing common public libs that include compatibility for diverged features to allow easier updates/changes to existing tooling and libraries 🤞🏻 

Let's re-open this issue when that starts to become reality (as I don't think it's good idea to re-factor `tfswitch` to re-implement what has to be provided by the parent).
Thanks for raising this for our awareness.
