### ISSUE TITLE
How to stop 'tfswitch' creating symlink to `/usr/local/bin` 

### ISSUE THREAD

**Issue by TiansuYu** [warrensbox/terraform-switcher#513]
I am on enterprise laptop, do not have permission to acccess `/usr/local/bin`, `tfswitch` will try to create a `terraform` symlink there, which is totally not oki. Is there ways to tell `tfswith` to add it else where, e.g. `/opt`?

**Comment by TiansuYu** [comment]
`--bin`

**Comment by yermulnik** [comment]
You also can make it permanent:
```shell
> cat ~/.tfswitch.toml
bin = "$HOME/bin/terraform"
```
