### ISSUE TITLE
Terraform some version missing in tfswitch

### ISSUE THREAD

**Issue by flex-yeongjunchoi** [warrensbox/terraform-switcher#515]
In this screenshot, I'm unable to install or check for version 1.16.1 through tfswitch. 

<img width="250" alt="image" src="https://github.com/user-attachments/assets/0d852e00-e0d1-4567-be20-c199439d5ae1">

I understand that 1.16.x is an older version, but I’m wondering if there’s a specific policy that makes it unavailable, or if this is kind a bug.

My tfswitch Version is `v1.2.3`

Thank you.

**Comment by MatthewJohn** [comment]
Hi @flex-yeongjunchoi,

Do you have any configured like a custom mirror?
What versions are available at the top of your list? Recently used versions are displayed at the top and are omitted from the full list below.
E.g. at the top of my list, I have:
```
Use the arrow keys to navigate: ↓ ↑ → ← 
Select Terraform version
  ▸ 1.6.6 *recent
    1.4.5 *recent
    1.9.8
    1.9.7
↓   1.9.6
```
(with 1.6.6 in the "recent" section).

Further down:
```
Use the arrow keys to navigate: ↓ ↑ → ← 
Select Terraform version
↑ ▸ 1.7.1
    1.7.0
    1.6.5
    1.6.4
↓   1.6.3
```
where 1.6.6 is omitted.

If this isn't the case, could you try running `tfswitch 1.6.1`, passing the version as the argument to see if it installs it correctly?

Matt

**Comment by flex-yeongjunchoi** [comment]
@MatthewJohn 

Oh my, it was my mistake. As you mentioned, version 1.6.1 is indeed present in the recent list

Thank you for your kind response. I'm really enjoying using tfswitch; it's been incredibly helpful. Thanks again!
