### ISSUE TITLE
Listing terraform versions makes terraform bin unavailable

### ISSUE THREAD

**Issue by jiraguha** [warrensbox/terraform-switcher#53]
Hello,

I have just started to use the switcher (**v0.7.737**).  It is a great tool :-).

But when you list terraform versions with
```shell
 tfswitch -l
```
You entre in an interactive mode where you had to choose a version of Terraform. It is no really the behavior waited from an api documented as a "list." The less convenient aspect is that if you do not choose any version and you enter in another terminal session, terraform command will not be recognized.

I hope it help

**Comment by warrensbox** [comment]
@jiraguha 
Fixed with #68
`brew upgrade warrensbox/tap/tfswitch` to get the latest version
