### ISSUE TITLE
ARM support?

### ISSUE THREAD

**Issue by sigkill** [warrensbox/terraform-switcher#56]
Interested in running from ARM hardware, but it looks like it's not possible at this time.

Any chance you'll be releasing a version with ARM support?

**Comment by pkolyvas** [comment]
For some additional context, Terraform itself is released in two ARM flavours for linux only (32bit and 64bit). We expect to begin evaluating darwin ARM support (OS X) once Go supports it. Just FYI.

**Comment by warrensbox** [comment]
It should be up-to-date now:
https://github.com/warrensbox/terraform-switcher/releases/tag/0.11.1071

Please open a new issue if there any problems! Thank you! 🙂
