### ISSUE TITLE
facing the following error while installing using brew install *****

### ISSUE THREAD

**Issue by Shafkat-ali** [warrensbox/terraform-switcher#57]
`Cannot install warrensbox/tap/tfswitch because conflicting formulae are installed.
  terraform`

**Comment by warrensbox** [comment]
@Shafkat-ali can you try `brew unlink terraform` and try again?

**Comment by warrensbox** [comment]
@Shafkat-ali let me know if that does fix it. Please and thank you!

**Comment by arafat-otto** [comment]
**Warren Veerasingam** it worked for me
