### ISSUE TITLE
No new versions of terraform - Stuck at 0.12.8

### ISSUE THREAD

**Issue by Nornode** [warrensbox/terraform-switcher#58]
I'm trying to update to a newer version of Terraform but I'm unable to get an updated list.
I have tried to reinstall, removed and made a cleanup still I can only access 0.12.8 as newes version.
Same result with `tfswitch -l`
```
tfswitch
Use the arrow keys to navigate: ↓ ↑ → ← 
? Select Terraform version: 
  ▸ 0.12.8 *recent
    0.12.6 *recent
    0.11.14 *recent
    0.12.16
↓   0.12.15
```
Versions:
```
OS: MacOS Catalina 10.15.1 (19B88) 
Homebrew 2.1.16
Homebrew/homebrew-core (git revision 2a800; last commit 2019-11-20)
Homebrew/homebrew-cask (git revision 598ff; last commit 2019-11-20)
```

**Comment by Nornode** [comment]
Never mind! 
- It downloads the new version if it's specified with:
e.g. `tfswitch 0.12.16`
All good now!

**Comment by warrensbox** [comment]
@Nornode 
If you scroll down with your "down" ↓ key on your keyboard, you will see version 0.12.16 on your screen. 
```
 0.12.8 *recent
 0.12.6 *recent
 0.11.14 *recent
```
are the top 3 recent versions of terraform that you have used. It will show up at the top of the list with the word `*recent` next to it. 

To see the rest of the available version, simply hit the  "down" ↓ key on your keyboard until you see the version you want. See the video posted below:

<img src="https://s3.us-east-2.amazonaws.com/kepler-images/warrensbox/tfswitch/lastest_version_exist.gif" alt="drawing" style="width: 170px;"/>
