### ISSUE TITLE
Add versions.tf support

### ISSUE THREAD

**Issue by kpucynski** [warrensbox/terraform-switcher#69]
For now TF version to switch can be automatically taken from `.tfswitchrc` or `.terraform-version` files.
In the meantime `versions.tf` file became de facto standard for  TF version control.
It would be very useful to use already existing `required_version` from terraform code instead of duplicating this info in separate file(s).

**Comment by warrensbox** [comment]
I will look at this today

**Comment by warrensbox** [comment]
@kinowarrior Does your versions.tf look something like this:   
```
terraform {
  required_version = ">= 0.12.9"

  required_providers {
    aws        = ">= 2.52.0"
    local      = ">= 1.2"
    null       = ">= 2.1"
    template   = ">= 2.1"
    random     = ">= 2.1"
    kubernetes = ">= 1.11.1"
  }
}
```

**Comment by kpucynski** [comment]
I've created PR with code that checks *.tf for required version and uses it if found.

**Comment by warrensbox** [comment]
Not released yet. I am still testing the changes.

**Comment by warrensbox** [comment]
### Use version.tf file  
If a .tf file with the terraform constrain is included in the current directory, it should automatically download or switch to that terraform version. For example, the following should automatically switch terraform to version `0.12.24`:     
```
terraform {
  required_version = ">= 0.12.9"

  required_providers {
    aws        = ">= 2.52.0"
    kubernetes = ">= 1.11.1"
  }
}
```
<img src="https://s3.us-east-2.amazonaws.com/kepler-images/warrensbox/tfswitch/versiontf.gif" alt="drawing" style="width: 170px;"/>

**Comment by warrensbox** [comment]
@kpucynski your changes are released. You can upgrade with:   
Homebrew - `brew upgrade warrensbox/tap/tfswitch `.  
Other linux systems - `curl -L https://raw.githubusercontent.com/warrensbox/terraform-switcher/release/install.sh | bash
`   

Thank you for contributing!

**Comment by kpucynski** [comment]
@warrensbox thanks! :)
