### ISSUE TITLE
Default terraform path

### ISSUE THREAD

**Issue by odbaeu** [warrensbox/terraform-switcher#79]
Hello!
thank you for this awesome tool!

I struggled a bit with the default terraform path. I don't want to place it in` /usr/local/bin/terraform` and I don't want to add `-b` or `--path` for each call. My first try was `.tfswitch.toml` which solved this problem. But I also want to use `version.tf`. I don't want to use both `version.tf` and `.tfswitch.toml` to avoid changing the current version in two places.

Here's my current workaround. I use `version.tf` and in addition I created the following alias:
`alias tfswitch='tfswitch -b ~/bin/tf '`

Maybe you can get the terraform path from an environment variable or from a default config as described in issue #71.

Thank you!

**Comment by drdamour** [comment]
/usr/local/bin is hard for us in the ubuntu crowd

**Comment by drdamour** [comment]
another option is to put tf not to /usr/local/bin but to wherever tfswitch is by default, since i put tfswitch in ~/bin for the same reason
