### ISSUE TITLE
Support mirrors eg Artifactory

### ISSUE THREAD

**Issue by jontyq** [warrensbox/terraform-switcher#81]
For those trapped behind a corporate firewall, we often need to mirror in external resources.

One way to do this is to use a tool like Nexus or Artifactory.

It would be good feature to support the ability to point to a mirror, rather than directly to Hashicorp's releases page.

**Comment by jontyq** [comment]
I have a locally patched tfswitch that works with our Artifactory install (hardcoded)

Changes needed to work:
1.  patching of the hashiURL (in two spots. :-( )
2. patching the version regex to suck out versions, as Artifactory renders the page differently to Hashicorp (and corresponding strip regex).

That is MVP to get it working.

**Comment by jontyq** [comment]
There is another wrinkle with tools like Nexus / Artifactory - they are not full mirrors, but rather _cache on request_ .
The impact is that `tfswitch` only reports available versions as those which have  _already_ been requested via Artifactory.  

Indeed, even specifying a specific version to install doesn't work _if not already cached_, as tfswitch first checks versions before trying to download the requested version.

∴ further design thinking and changes are needed, to have some sort of "try getting this version anyway" logic.

**Comment by warrensbox** [comment]
> I have a locally patched tfswitch that works with our Artifactory install (hardcoded)
> 
> Changes needed to work:
> 
> 1. patching of the hashiURL (in two spots. :-( )
> 2. patching the version regex to suck out versions, as Artifactory renders the page differently to Hashicorp (and corresponding strip regex).
> 
> That is MVP to get it working.

@jontyq would you be able to share your patch in a separate branch? I would like to look at the patch you made in order in use a local mirror. 

https://tfswitch.warrensbox.com/How-to-Contribute/

**Comment by warrensbox** [comment]
### Use custom mirror 
To install from a remote mirror other than the default(https://releases.hashicorp.com/terraform). Use the `-m` or `--mirror` parameter.    
Ex: `tfswitch --mirror https://example.jfrog.io/artifactory/hashicorp`

Download latest release for this feature: `> 0.12.1168`
