### ISSUE TITLE
tfswitch slow when switching terraform version

### ISSUE THREAD

**Issue by mickmorseMB** [warrensbox/terraform-switcher#82]
I am running WSL 2 on a debian distro and tfswitch seems to be slower than any normal linux OS. No doubt it's something to do with WSL but can you shed some light on what is happening here?

Cheers

Mick.

**Comment by mickmorseMB** [comment]
@warrensbox any update on this?

Mick

**Comment by mickmorseMB** [comment]
@warrensbox any update on this?

Mick

**Comment by siran** [comment]
same here, very slow for such a simple script. something wrong must be happening.
