### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by mariuszkopowski** [warrensbox/terraform-switcher#83]
when installing via CURL on Ubuntu 20 or Centos 7
curl -L https://raw.githubusercontent.com/warrensbox/terraform-switcher/release/install.sh | bash

I get fallowing info
install: cannot create regular file '/usr/local/bin/tfswitch': Permission denied

Docent mother is i'm running this with sudo or not.

**Comment by mickmorseMB** [comment]
I needed to run sudo bash instead/aswell, so:

`sudo curl -L https://raw.githubusercontent.com/warrensbox/terraform-switcher/release/install.sh | sudo bash`

**Comment by warrensbox** [comment]
@mariuszkopowski 
Can you try:
```
wget https://raw.githubusercontent.com/warrensbox/terraform-switcher/release/install.sh 
chmod 755 install.sh
./install.sh -b bin-directory

./bin-directory/tfswitch
```
