### ISSUE TITLE
Add snapcraft installation option

### ISSUE THREAD

**Issue by warrensbox** [warrensbox/terraform-switcher#90]
Add snapcraft installation option

**Comment by versus** [comment]
Try it: 

`name: tfswitch
version: git
summary: A command line tool to switch between different versions of terraform
description: |
  The `tfswitch` command line tool lets you switch between different versions of terraform(https://www.terraform.io/).
  If you do not have a particular version of terraform installed, `tfswitch` will download the version you desire.
  The installation is minimal and easy.
  Once installed, simply select the version you require from the dropdown and start using terraform.
architectures:
  - build-on: arm64
  - build-on: amd64
assumes: [snapd2.45]
base: core18

grade: stable
confinement: strict

apps:
  tfswitch:
    command: bin/tfswitch
    plugs:
      - home
      - network
      - network-bind
      
parts:
  tfswitch:
    source: .
    plugin: go
    go-importpath: github.com/warrensbox/terraform-switcher
    build-packages:
      - gcc-multilib
    go-buildtags:
      - tfswitch
    override-build: 
      go build  -o ../install/bin/tfswitch`

**Comment by versus** [comment]
https://pastebin.com/dMwvqL81

**Comment by versus** [comment]
snap install snapcraft --classic

snap install multipass

snapcraft

snap install tfswitch_*.snap --devmode --dangerous

tfswitch -v

multipass stop snapcraft-tfswitch && multipass delete snapcraft-tfswitch && multipass purge

**Comment by warrensbox** [comment]
@versus 

Thank you for your suggestion. I used your yaml file as a reference. 
Would you please verify this works?
`snap install --edge tfswitch` 

[![Get it from the Snap Store](https://snapcraft.io/static/images/badges/en/snap-store-black.svg)](https://snapcraft.io/tfswitch)
